---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCXf529gJh7SbF6dhdDefCxAtWFWeT8igaecHBSqn5IkTiPSVhKLqNgX1lW801W5B2mrH8duXxVQBMjAmhyAWiZSIsaoPwsbq/1iuJ6O2umVSfRHEQB4YCrakfOwmGzAkLBSu5xtUgPuJx3cbiyC1Lg2vNH5ho/4ZiKzzkINAwxnytL8jDQ1vL+S81IR8ie/rMrneko/YLWF+es9wKY87qnlcGjJ2O3/SCwoHi8y0mNEoTYAMEJK26FcrCW8RHAZB4oeA3bvBmonyoFQQL2wey6DE+wNbhGOXLFOsMrB+1y0s4qnLRLB/UKgLD5B1MjvIuixv0K75Mj1j/JLUIA9Q0yNYjXUXm1k2a0NwGdRdxAoIYJN6j/HQE/7+VbWjn1llGqDZ75Fx4AxM12P05g1IffDAxjktRpryHTkHzkLA9sASEJYL67GKLXkLD8uL6qQxpr5v16Ovku6m4OdYUry5NgzqV4pJoCJnJqQoudQIKWgL7lrOgA1eViZbQUxYDI7XlnYxnJoRCfPmAZBd+So5BQF8LGaE4FqQNqEoD9ltuYAZVZ5dkyYmc5rHpytSM7tKCM/P2rjefBU/ScLFEKOKvelOnGOD3HO26yOC30zq/a40dixZAQVsfkLT9FVkb6HiiTwK4S6d1AkKUoXZCqEDTzoSlDUeJNzWiRFFH82QlSvxMZd0ghB6+ZDV7shgKF7y/U/9RFE3WuC8Ii0/2NJnRQHxmkIqVrgGdYPImJ1bsWgF3N2dPgZsibhb7ToaynD35y4PGjjKmrmP0Ckc7Dojtr
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
