---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgATTAvczjUvFM2YAv2KzvlwybrpSS8koW9Dm99qjIo8A5cCFT/hcXdMsllUXrNubbSi2tf++UeH7KjVBDCd4FAzhQMHudN94cwsURm+04owE1VudllIpG16pVNCFCRJC8bgPkwUo0fb5xKxI6xJvngWRpzueBCRvHbHYg+WAtTpw6Mhcx8xmorGsSBOG4MZzg8HPUH2XC27vkHX/XUkktNnDlfb1Q5ZUxwac8/36ongVAfBy+IYmpL98aTO9lbmK75qxVkjwf5Gp2RP+rpqKrmzX6QFYG1FezfDBVAdX/rHoAaW3Ahz6TNuNz6rCisneNs/kN2cAAKLooT1HngswI3zdjGfKDsovhp42+VJ6rNHdB8PjdWpBYPcW6Hsl4q1rw55DA9YQ26/K92W3wAuLWkESp74N/OA0S71U05sX+AA8P+UJRr2bJ15X0t8xSyE+oQlbqGXp0e4ZVfGOmSctlD5PjwFJXXRckkO+QNUVbjS6eVCdXyZ1sZImSthFFbuRq35LKBSjQzuTymI5ZoDzBVgY/qnmAA1GaTWfZEcKL+6g+vgoOm+Ijgh3SjAPtxe7uSK5lvs2C+idqMM9K2pb8O/7Tjs3Z+e1g0ov6U724IaZvwLA3FxPtzmABm1zE8bo1sx0BJtIS0kRCOouBNNY6W40GfDXQ5DEFcjjI6XYpwhJAo3ASUPvQ7or4o/B2KRx7gbuSOxR2geZ5/LFW1HtCL94BMbmi4WjwPtQri0oLKD/HCW0JgyHTOOicEYZRsiaFoduBH4BXiGWG4s0TktMYIE
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
