---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAVysnEXtozNjNHiudE31G34oHXPP8i2Ge18e2k2Win9dDsfamEb+kL51jDzCc7tfNIk4EGNN4nygo6xg18I7xFC9JpP+Xd3RUN8V9sp/frJF2AGIyiS3H5jdMMxDQ25tGHh6x0mUNLuJe7hIvTNgintVB3ne6UjRnKZHA2qHfvVyPEqh3YpZ/3j0NrSZfAhOVr9dqDlCqlRLkzHAI8F9cEchzNmNT5hfstF0UXk2dSzH/WxReOeBKQnVprofGWP4PWzkYc2XyU8X3FDwaC9wGm1HjSAd6sWKpEcxmq693AbuF3+mwspzwpKcyof7dFiEZDE82luBGxsAB5+7/IQgymnyoRZXxQENJPrbJptpp70DQA9FM42QlmvdBO+agTBfWBVJxiRlC4RGmOBnlrpFqd14DODm8A8m+u8mlm4Wzdf2bUNihIOIr7ZHdyOkMZQG5q0Xc6FYmuQPcU9S6R+jJtTpX6/37OCCFsMX8k2lw+hxwENDN/GAPSalt4h7T65aFZkEN0EdqxP5yLYiLUkhILevP44lE9Jyd06sE4FI13TVH8Mo9oOpEgc/eVrBzJCQT76JyFHqNsSSjnv+As5bQVQYpBTX8aQLtrHJ7zGpX46Z9pLRRkAdcLjAY06EIpcpgyPIRu+wMjeUeUAP1EudkQXemKkDStriC8VBwJO5pq+WLQLothIYuAz2rZf+PJlITWp8KRCq+45ENb5SshvMPsCXrbU1STUVrxHlaejx43tvRmqtKKAICTFyj8Ye9wtOQAsNYc5yNbDdFzM4cgjgGT
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
