---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAl5AO8bFyxeQOMI1x1Va11IgdRN7ghr4QU7MuE/8vKeyvXPz0clGY82vKcEFCYZdI1WpPNIOF+zD7kLTLs0lose6sOOPDBajbHyTQAa04z9B2hltOEKEGMukfpprkTunF7KFBfFLEmoVBmtfCOikKZLFDPRbjuHd6xThS0wzkfsXuMBVdv4cZoEgGhc3DQHZAt4SOl0RskFfiH1kS9/hBnOiYOdNxSy4Y/TecqrAxaFsLSkk+EHw/aFDz4i6EEyMXlIGNLxTtyhbSmRqKxQhvAWgwcdj6e5J8tlzDZbLgUHBJJZvyLu/tGRSkvAPuSerSUSm7C9LXpPgzgtZ/9aFOHK3nG96eSaFB/KdvKO/Lp5gFZ6x39qrBaB/5p+fXhAdEzOXh4yrpjK4sFFMyLUkoZzvIMiTVEKiiWDdHLYF+niQidVC9e/7Fv/sFoTYd14BlRl1rv7Odf3jOA1e5PRXggzB/GucU/s82stYHH1dY2g6C1/yarZ6ymFzkwcLwkVNoCLGDtCjX/wdraGM9GC+Z6zMq+PQiF+iWa7M59ix1YAoaLkSTRiNjYKq729QTP3k+X4nTYwS1zI3eRcnge8VlSzvou+JiB82xr7dG419e7MII2cwcC4cTy2o6q+kYeqZDOY1O1mQav2tUbqwWCiKzYnhkrNfSPqgYhte6LAs1FWrSp9+rPDo8Zn+CpEBWLN8P7k8Ywp3jrOKrUhbRHYYijFvdkRGQeWgFrhGPuBh40t0JNSVHqXMS2p3n/kpbh1l1xzj9EnZsVH50aKzSF3yWk
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
