---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBrsUr4emJsaJl0vXp5T03hPyuOOBXOjw7JgawFwoeoilTeBVXlqXRIgEthvZ3Rn3q5pMRkdl1Ogkj9JpMmLPKPnCDP502wi14I1xKU8hJz45ei/d/JQD8/Fn+ElPDRaC+SP88GO/4tkpjwL6DyGPRe4XAtffELoNIvudthakGnj9xsVQisUVIl3q52sA/n6As9XZh6euBTSl4QN3Fho8ZMGJ4ytXnEYCqgpHOWuFOGBwHX4WPAm5zkOgOTty4R4Oeh46ujkgmyr5L7Pomd7TTQOj5CT/aIjMQo9Y29ljLYDh6rXvlJ+mcen3X2j6w5mBOihnvIf+nJeZ+AX/uBMB48yeTzfk5ZJuP1OcinV3yOXj06WS1D25RQqGeaY3HHOU2MBi7IJftCS3OxuQ9ZtOYlDeH24nv66TV1A8vAFgofpageMObNle12mg2oXVY3JPSquZ+384dU6chCBZwH9zM3kC2PTDRtrOuVAW7Q81VFyDfyFg7KuGvzF7+3TW87F7P09UKJh9lBxFiUWvDpHBL99YF51jIo00/HLk0+mWHT5K4bVXTOQ+58UnHqB3n4D58PWjEvrl3Iyqc07Y2kc+/FSkcTWC6PLLWWbRv/HkCZdM9riAG8LFDyNkAtxLWYRrAcVZBrFrILk44+2pSmsq8Ab/vdLyyBQwzSUOXhAJj9mL+v8GKBjFFM1VwFeKIo9vcx6NqfcRHHjsMUL5SotMbhAbqZtOBdlz5eS6SD7G8pZjtxKcGSDs3G7SgXSthjDmX2CI8cCpUKiFibzfStc8pV
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
