---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgADJxG+YSnslbtLfCn5V/sh9p78b8RT0FmCZzNn/lAYD6Fc1kKps9UNkMJRMlKrl/IYu3OiNeo7dcN+eujEjljzQVuTfqXbx80jYpwrAh5hNZnU45a2N9Yy/gqP10RMIteiWgMvYt9bfmfz1quSY7aoDV6p/NqyD7PAkFJgKyHL0yRJ9/7FbNkG2kOewbzVOlMf6gb11yPa5vyqevTH8bZFY48EUIC/Hm6c8+9d4ORmFYw//20+YrNoBjwCTXljOQQIl15u8KvzK2wyDep5FjVWiPQGH/1sECZEDmA9RiXsDYwOQfGXaBjpO4XEPiffcjQKxmwnJThzfPwOEpPTzE7zHZXAmEkTXL7W6LU42iGYvxekVZg1ZE/K3N0bVJjv9enKGq0Y/yftwSmuT5WJee7pHs65DQGaSxwKN7MSSGEq+ScK52gwO1TJLfjF9yMYsJnjNg7k4WSa2ocJ0wbsKb5ghQcnDSJARohqGDQA7pUMB0+D/BqW0m71Y8L4mdf38tJC2A7Nlykh5+6xTrROcSdKLOy/zwqMu4KxugLIrlmXpwHvkryYm7JfTfZzPKId+xSDrAq8Ii6r2AWUQCoC2tYGLklo25DgHQdpAgp546DFeAYHs6SZb6tlFDgmEuDRJaWS+SNXGc51VAPNMFHCEFsIdtXi+/ks4C5FqBK4o6nhBm/zCF+g5kulIaH63Fc7oGuRGZmw3Kj3YFDV7/jc5RqgzyhyWtbHz+F4tFAW8G9gHznv6Cx4Qc0dFnfD2s2d3d1xLZZ32sG2FnAqO5dEIqtK
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
