---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgB6perxD9Nza+xbyk7hgFc9Mkv9BeaEG8aZDGiWick11dKlxeuC+qlGovNNJTIWaI3sZs+BOlo32sblNh8IODYvUuJkeTKDaU9J1HOlYbObEjazCZKGOz5MRRsre9oWJGeMAsbbQ6MxIv2sDwNmQSBRebcIDU5i8RYm/XstuoBs7KsZ0nup+wrPqMl2HlE3J5YlFaGjYDGbmru8bxY+070poOze2SjB+6cR+zGULIlviK0FRpkEXFIiLl00j4P7ecqlk21FQuyiTA7Wcsrh9KaHYl4eXAG0jVgoia015rXb/OycVbjdTGitwTa4ELZp0LmcFmGqpqTiQfoQirG40Gxc+N3m1TWW3VTRIRvXHOkg1ddFmAbIGiUNKCsx/st8+GHZfGUD+Z9kDTqEn0DKiGRJIuK3jqeQOQmhi2EgMMfKltJtjZNGaRvV/ePCSuptnDf601UKrfJDM9NOjzw8wRhASKmmgSJwX7hY97BQBJl1b/0aPgn/gVxczBb9YihU6K6A5QqzcDA5LXNzz5MpvhU06u5JkGMRrLXPDs1Kap2yPzmznz1nIIdJddSH+fUP8AmLV9Iw20Du3D3cc3ZuhweIjLpRCUUg32362Y0wYf3A3j5ax5KYjiHV/BdXQ2lU/6K9aKon71g6jORx+7j9+vyp9xP3FLjZ3Nn1ZOmTyQojuS5hI2rRwXafLmTghbnuL4kUUUaVwy6MOw44rEUeZ4brbLrUR+VgE6U11IDLdKRU2bc9Z6Owh/2fAYMFmPOj0coCrj9dbirEFavRAbHopKjG
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
