---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAWoc2FzCDbnbOrQsvfc4AX1F/hBMWjG1rzPoY/QEizJDJ+Qoz7kClKvSHBL6pL7W9KHK/Kilgnh2cefJVSwaf8ZnXLS0ZdwpgeVwgbg018pCwvfK76zqD+QmXmAsJ/UqEpBaq6apYdtvhDqLcQLV2ggUoe0J3oV27K2l3r8WFlJu9gGUzgRda+AbBDIyju3+Y/+eyWRe63LMf2eCMdendcIjKvLkMg+8St1T8AuW20suiir1vFIW+k+cRPXX+yxC+2Vcu6N2Kj9sjVDWPBVMzEhP2Cmbgx8r5GoQtcKwHxPnAZQ4SQxy4BFdtsIcy0oQYG1ocOMZ+nDgmZeOTsfJ+90BQmycyc7aL4ajt6zO7vxIFICYFqoAhEnx08nIR8xv5EYMcCIDhEcas7516G2gnm9MODiXg/NOkXC+t/Ao6Wnn8sinzOXhK1zwAPHuwQptZERJqBzCVC/ZRRxlWeD1yVxT04OPcI/wjiqaq1Iin0pfmB3zyGeykGiTWdvK/PKgVy8jiOMYAm4WSOgHg43gewwVy1yU3ai7d5kS4ASgoi1WD+i4djaBxDOLiRJ7eUfcmu+eiq1KgC42UX23P/kYhG6NQH/znkK4/0J8QRNt3ihA4E+wYtGnjatEfjGXAoLolqwxyJfhPkExItBUJUDmnZFCgWvMZN6kUBmjK4smY9CzqJMp+1T2kAN5dGRbqlBH7m8f4wwUWhP7K31Ylc00RmpQqClLv0DqYnj+a95N5y3ctMt8zTL4ejP00WL0pghd0vhHOCTHjuKQQ/oWhlJlsf
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
