---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teleport-kube-agent-join-token
  namespace: obmondo
spec:
  encryptedData:
    auth-token: AgDZqEUSZM287y5R38vyGxl9iCAHsksN+SSTN7pG8PrTiOGPgx6Xu5zNazMJKqlJNCtX5zLzyzfQ+6wMQivstqiGAYx914dWcGuisJqDrnVaOLIKaHlyW66xqoFiuxp4d5Wiz5ZisQiBCrX9sRdYppokFVGmGFtl+dt2SX6IPkbYmXXlFi5HRtA6i0DGsfRCGpMOfo6PRYguR86ORtaJRLksccwqGwf7b5BvJj2/PGAB1Kh6iwtlAfiTQmMUL3HaOjXDjxXYvv82aBVsgLjDsoAMFhAD5abwOEroyB1ZUhh+8I8DmpwzCa1fvWKKkM59CVSJIHO5TDLtQ5FwIK8zcihwVETEKzgKNPiIGu+6wY7FXR6nX/GJsAWUfgYK++C2Ml3H3/boYOKxvafeCzT1bnkAjLZ7H2H5tK56dp2g98K48VtlH11W1fpI/OD5BcKQ1QpoBwRDZFAsnSvgfu5oEn/t5DURltPJhekb8ZzlDksBAXST5ch+2JD1sbSDQ7b2S9Vz4y608mSZd7ke9eJ4+UchZ6clK1F4bWCVG4JBrB+9KP+3+TR8GS0uDall9uFWOTtleEBDQ05zi2/nR1mwJN6L6yGOSXVOnN6sdTH0zEUlkvevVPJPVXwetfMxjuZOvnscQv3hFuL+wH0PV5rMAA/rExfOGoMiv/b8ckCZ6/HnSbp3H8LPnZXD7bxU6lH+s/hYDrsmfAQMJrRGuoeG0f6bJYsxFO3iJDG6K3sBIOKYdw==
  template:
    metadata:
      creationTimestamp: null
      name: teleport-kube-agent-join-token
      namespace: obmondo
    type: Opaque
