apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: HEAD
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: keycloakx
  namespace: argocd
spec:
  destination:
    namespace: keycloakx
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git@github.com:Archisman-Mridha/kubeaid.git
      path: argocd-helm-charts/keycloakx
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/vpn/argocd-apps/values-keycloakx.yaml
    - repoURL: git@github.com:Archisman-Mridha/kubeaid-config.git
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
