apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: HEAD
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "1"
  name: root
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: kubeaid
  source:
    path: k8s/vpn/argocd-apps
    repoURL: git@github.com:Archisman-Mridha/kubeaid-config.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
