---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB42OEgux2NHZtTTcsFug6+eTbXVaEZ2hJmzNjEd8uPKueb7KgGO3XaenHTDO8r5c7BZzBfm2prwFIlUX7/gHQm63vZ0TEf00JJOsY79coOIBGA4Jo8/4QmmGzXZXTeZiHOVVu6xm/WVsCN/kYO9TAs6eW2W3bMRnMquxhTTCECOph6k0M9xtU2gHGabWXLD2qvkdBu9KCkiijZricH6Lo9vZmYN1+HmCth7lI5qqzBS1fPR7KryKq/+/6smFqGexgKcf9WW1xTWGpiglHxESHfnSyTnrbIz8adgJUqwQMOudf+pb4u6WYmM4Nh0cK8n4SXTGQBlX1WPjM3QQve0OdVm2SGP8vSHdNXH6kDlxxi4uXr5mNr+vTZNtU3ZIvRnXNnAVaaOwj19e+p0aCFA/H44Lx6POEErgJ+SnQB1MufBbPuAywf3nLbuKB1LHGSyvy5DszBLJltfjNNJc5O0ECOjVd7IdRX/cG4IczIo8kE+bQnm1TGBDyZA95SCZyuzKI59KG3weVOdGiJuml48f8gebPbkgnxW9T1ytlQ/rl9X2+M1wj44Z0qO6mKLomu6rZXXPAHgJUQR6HCdH3RjKUvEOtuE2SSnVtLOwzW+IVDpOExUlaGAw094q4GUkTOc7Y1TAUA76WIgZFr4v3UG7EpQwb3W8YYpjggKlFr/z4+QBMhVPPbq4Qwgmy+d28Yxg3CXO7Yw5q62Dg/UJvEbQucdUns6GjrU2yX5TlbNP1bEcjNLqYig96xySIg+n9ESGlUGeGI5LjVjlEoOSu63M18
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
