---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB9cJp7jIUZJymrDUvHZ4fK7p25VY+a5lovmpc9Oh0jjuAsllj47j2BQw7X/2a7CHmZFVlFDkTFLcq6yR310Qxo1Pab6DF9n1ztXO5qg64eklISm7ehMAOsyfiY7KOl4r8yOYSFEyHjf2Gi9vRYQeg/pyvZqtiYD6JUxDnEQSYx9DpfPvrkUkUf15YKVhkFCitq0NDizAyj/T5TY+jgo7U5oVvjW7EN56zfsk5KrdziBmNOEWW17uAeBZo+g/2mpFd6WMzdTKV8v7UWkoDvZjxWheqePagtIGOsTDS7592kHJSQ8DiXHdtkcLfQjBEQciLVR5zc3bLJN2YlDoCOg12BKt+vvL9S6gUIoZwqbDZpmwvwxelvxJjIJliIy9Uh14Tbro+W+YblTdjj2/3eICV8AYJXa1dUitHL93GTyhPvMVhruNBnDPgYFvxgZvmDonENhLiXQYuZ0Bj3kjiOsb9qet+iOZiihUAJrj+HGnc8eMI1zjwoJvWTt8+fRjUCc+5rBO7KszLnVyQixaeR0GNn4ZcmbxW23eqnWHIJbK/y0QrsuxF5KmUd4vjyzxqFKVKHhHE++T4K/k2NrDmPGoNHBmH7pPX4mbmjvLiM4xkLo0gU37pn7ToCDElz0Lxw7eCsIs0EHbo6gxn6wlLp0Ddiec6RWYWNf3IGp7So+mQ1/cCu3Fx61nmAe209ZAf6lyntLULbqnTIYdB+7s/dx76b5mg6AFVmkdNFgVgnssFCb9k8TKmOmChkbgcIwtIpjSDhRt8LDRNKK2Nu6hTci+m1
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
