---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBfrVQD0nRLfk9Bx3b6/Awvn3qJZjz6VbnimpYQ/KJM3pVYmLIB86v4CZVtttXYVWM+J4htf2RCVrrFjLIFA8W8Vxb6dqDbYl+X3zdD/mq1A0w54ncznf5RzTMGsXEHiKVVa5myILIN476H41mZ4YzC4GUlDQYP6r6sDQ9FyU456UDqrsscazqzDddrHTCqfxwqMDItx3QLT93uNYuoDIzCoHjY2bJou2jPnhWnAXp2h49Tn9XobuzQ/GQkgn41IqcVW3v7VEGJY3dx04UUR2sDgnwZCqSNVQTbckR5VK0ys733l69Bji3sByjgHitvJiV19TCHWfpAF9ShdX7oi+4f+NSK3YiB84WuUUNAsI+g2Cm1lyoZwsofuWGsCaA4NnUt4xV4MRb3du83pY08/1/RkUcrG6kfG4ToQQaaEdrve0Hue/l2CX9ZVpyncUqi1mAMWMiLvW5PC9FZPbSkW8p20NqUTkIBYpfF5h8PG6cE5o7oyNa4GE1aYGkcwesHklKh0TQ0/Yuf5AeGAgvm/p5oDu53BYfEW9665Asd626825sZM5X0k63eneu8qAiIAn7MXu1rqnUPXYSj1KLK9yAg4X9WKbs+wkaQ1Wn0fpgep/5THoNqxcuZMgb53iSxrtfYHWX/cHzuq5ivciscdYWJpIayEaNnJP8F/7t6ijsECVajbspmgF8yJPE1QI30uu/odXI3Yrb6khNt55Pfxd96IqYWBA8LavOP1/Ou8JsQ0MK5/BWUch2SzIFnKHXLtBRkSjNYdkVji3aY7VAfL6TT
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
