---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCApRyQkleUKeFQhtxkZErTYh/Fzv7PWjHPaugXj/8jxz28jso7Xc440F0AXD4l7Icl8dfdRgYoZqoTEMIIPHCD3HRc1DSjEOB3tHHnbsVyxoJ0Wti+RLTGjz1BnLNME2gId/IyCurbfS1fKUQdUdDqva3aot5wZM3hN9XHy8+c7oc8dtXGPx0tzRNynZtB6HnRN0+ex6cUr0GIDzDCQDe8uIzMf1+AyXAYPvye3bCzlIXnsrwWjFMnwnmhdK4JBOYjwxQcRFhp7FsTCcxa2sN4oqgayQ/nT8HKBhj6hN8S0mFZv4E98ncji2kmxonUtW49vuVTHWzelQUw17cBngkcpTLAqKK6U9DOl+KOD4NHZA6gYniGW9S0PXNh13/0T/RkURIaWrv5d6kqN6XY38bbgCSOYIpkLYtelOVOoghbqvicpZs5SZYSb0walJLgwgrZ88YhP0fwlH4uTlmMzmO9C6m2AKrkBpgyQX2ULBHiz2lcHytuLxfemcBH/GhfgxVPjzkcu2rSpZYa93bcMiOh3vKbS65oUKqgjduoSNLAz7LxEfWZEAUvVj1Geru2w7ZregIYCBGh/k2SXPgGe2gco/cN7MYBuk6xTDW68xMbgOCELvLQxuuzSirYRnQ1NAQdApkxwty1to5XhwWMTd7S1SfLjE/nUIKhBuqdncRE2qR564KEGyRreEr2aPRTbkciwA+VeMe2Zjoumh4SNbho5Q8imLCIu7ahG0Zz10hxnE7biPlLcBBpeDND7ArIM2AyPv4kGVRQ6EZQX0jXEgV4
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
