---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCVVrY70HFCXUc9dGT+RHd1Wp0i0uQ44CBL/0CDjaMdOeaFo7l0fsx+qx/d29YkJCF4s2bplhIqj1tRWy7ShDzigfQegmAlKjdyn3hAdL+earNXFUq/JCm3G2m8AHXN35yIrerDkvJkDQQDQHN/njJxNqq19ih+tM9cBQKWC1+lOwcO/ud++/nWRtGYNUSlFaCcTabalAlnPNHa1UzqwtMrLk1d3wZ8oHYHAU7unneD2kd15DE2hhY6SHMnJxF7HxsP4R1VxgwC77OftcFXo2h5iAuC95+xyW+nvONv4UbdOAiHje8Q3KHWbRyDCJiGStBNJEQvwYpMbejovJuuAf2acgvj7paMG94U1dtaHf7wc+ba1OA1iX/MzTZ8GIQ1A7E8I6YHY9iMKibOfNIkgkebd/acdNUQehsWLKr8lsUJ9olAv7KOjFgUm2SIo1em3UFoE6E365yr92RizS73WTSwvVb5mlBi+Z+3nabLNq2bu3d8NdcSyNFSffljtpXUDb4oVJIiM8wCrXsG5IejNyKSstFp2dLwB3JOSWoYrUxsxJf5XW9Ey+czljtia/yD3yqnIy2tHVyVWMyiyzrmac5tjE+RkWZNnNIMsqqoQdAKcNqJevU56imQ5OAB42Hx1nB2ehLSHHyLM5l60l8AkZ6kFf7rw9j3eKBjGgTG4d0UkYHwzEJqFwIRDnAaWOrJUT7DUaWFW+T/7rt+hJ0rFl52LkO6oeKJSp0D5mAoA6cekC9npuU3vvhRTPBPMJZD8Vz7A8RFKqdKv8Y3FrB/AVWX
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
