---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAYhtZpV+J43G5XgJIHGpC6xe3YA5dYNgg159QeT5rB2KHV50h0rVpl8JMqUFg7eO6M49DZt+gnWLYs65AMnPmRhra7rSALEdAghjjfWaw+6iDCA0DOgGltY1XP4Lf1xAESwqNEDX98hctTj8IHrxq0OzansNZEWKyG+QT+UxUJoF6YC9o0tjkT2DB7P/CSBtuMzPyzYBXNn0UZnSTE0NZEOZIZwl0ZiWXzQzFVMpWNhOL7CSrCPoToqk4o+uX5PyrKXV1dH9F4vUOWCA3ApV9cjxRV+//i4XL52+S/i0+mX8EZeDRezDZFw1OsAUP1gV4eDWnk3jg/+NJh8BAvBZ4b3XDf1BXXvzHRkR51hmxjdemx5bluTlnqGSimWKuGou5eomsEsuOzpxAhVAJxtI75MbOtje2R3VumqF1JHAHrXElBsGSf6md0wD5orxgQfvWIVG6dqP4TxxXO2zH3hXt87x+ZlLphYd28HSFnWeI6WADvNIJl47eux6mdQWjbUy12EosUp+mzSTPk0SFyOLpJemcSxgzGjRlzxolbrbYXquFGsvrHYgB5B8Ydh/jrgPh+S773hB99uFUDJhb+8etS7gh3MqFvFTn+CjZ+1+CdGT/1JABh7UlZUW2Uq+0iM5Kjh1TTR/VoLu2ijQlH8FI3jsmzqFpBjMvlZh5ekDYusN+Y0aWLQ0DFYQd66WatU6gOSOXBvP5OKppZGWt71RFMr/a2sWZr4q/+oqvFXuNB4YvbTV5or53CHQ6hRMGvn3XlmUhQEB4iOz7rtFCWy2zp
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
