---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgClgkKss1hrG6STzt5xGU8TwCbrTEs8rSQvpy1yrLN8niXxxGSB6PeuwUIxoE4x42njWqVfDm/cVNewIRdHJEd9ieUoBgIjcTHxdPkDboog5vdULi9heY0Xkq7xkCcxMso7/CDTeSR0izgvp1RZaTy1xbcJpuYfh5Pjm+UavjwSL8bjzA34W1Fg4JbhVFNBDDfQDWO8fpy1YFFZ5IZnCqiTKa3pqlrqA2f4TDDGnSftXa/kDCcpBAaJs5erzLrZlfL2iqn/RNZJaiBaAID9dcL7zrqbRQZpUNPZNT4x+WZ22M9vVSyElAO7cJk6OzIWa3B5dioVzI4x3xEm5xwnNwbUV9UsgcY/Y0U9lhL+LbeDDHCQU+ZnvjSySV68g4iynIqYI61ee9YET1PHhRzVsBNf8sTF8TNR6k3By35AAHdRyBVajjGdOmOJkx25pVm9lrpr6aG1E6Lm/TZCmji66UvlmoQ1r2lie+EdfHH998D87BTwa1t2/DVkARIWXeM5iO1CL+fabDB7dOPoTXzHh0ENt6QPjbxdUQ+LwCC6B0JPEm8bUdkGTniZCbLnHSj8KJ5gDcgwby3DheviqsVtuYXVj2kU6UWx2Dvt5HRbglWgdhMnynl/MqEruzxg3sroEwrzzp4UBRpW/LtGIsxmhrYKto/kCEGpUdNMXp+CtZIr2h2VCUXBdYqgyHctMtgUKiSaLjO6bHJ0A1PFkABFl2h2GbOglbcR+a715l3KcHUBHaWWZhbBISnMhEQIDGsi+ys8ZsIqJw+mNXyP7R0xokH3
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
