---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBl6xflP3TpBDCiTsH8FBHdcDDXcssAn2/YsukKDGuQ6dVIa1+P9Fb8iuW/dayErMzSk6Fi+2ylW98RhIKaCGesByLf7fo4TzSEnZVQxd+y/rsdEH438TZl1bNvFKOy5sJtvKLn0QQrwPB4dXz5p5laR65bs1mxFwkk8pLFpea0RgjMYdJPVXfV8SE7STyJgsYMP12iznL0GOCC7rPtoTrekztrWrgqMi4W3uHSUhCo4ReQxRwF7MKn6Gl13X0tsU7iNSMgUglbD26dRNBA0Kg6oyPviEXerYYK1qcl3IKvmfAFdwjB/frhRCZ6ShKBVxCRIdHDsWfTYQ5bG0kjmysS/UscA/NZT2yD6jDMyLTJ569InUE2hprvE1e34Mi+GTFnKjFIcWDlKuMleWTpR36lWQUkTdgdEnxUEH1OhF/o8bPFs5YcyxxLiZ9dt5zzNFCJxhhJWXf4D7IdQQOEAWHjt8jF0X9pzpAuMIJsNglMJc7lU5E/Kl4jI6BBZCWKP7hZ5MqoV8l1SyhwzUC9TmeFKvkRBAsJkzN9q2bPTjNCCugk51rbyLhHjZAYyEKcDc++kilxwujSWaVwbwyTrKievfw3PLInqqJn0L7xJeqGrRQio7DZ34S1iVgkxEY0PqS9CzfDtgDUftDi9DU+3XQd3rjii4tpVAemIA7/uSe1R5UPhR7bvH/NDDqPgODm6PQjlfAAvogEWUllScFlsgmwD9yniDZtfUwn9CEgenY6WfWiEdKYtWoEKaCgIacmGgYdnXZyFJZlz2mLKLHrvfkl
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
