global:
  clusterName: kilroy-test
  kubernetes:
    version: v1.32.0
  kubeaid:
    repo: https://github.com/Archisman-Mridha/kubeaid
  kubeaidConfig:
    repo: https://github.com/Archisman-Mridha/kubeaid-config
  additionalUsers: 
    - name: archi
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6dc7jP7zQT7qSKkFJd4pOMZmTb0kx8R29A3DbzLaDSSepEGtJ+64taQ4YI1C5/l7BFdi8blb1N135tRf54YY1v1plFDzukjxMx8GLa965T4YuSPg/1PhNQfsUcGDL/LXMktJiJP8pYvQKnOjM6KHju1GJKPlmlWHkttyFk6KmkeltF+ljPRGJhpOUjvM9RJgsYqiy6+pb8hGKxQi4dQ07duj7y7N/0pPbHg/BrtpbtHm2r/fsrFfzVwqIRg61LKxrcTZ4HPGpKPoare+X+wbp85hQOfWr6KtG9cQMjGbneZTYAYXhQxYlr2XlbGq/yj9mQJxYg/rEIL/EQY12An4zdI2hqpNlgkZwioc2agCGs3HvtQY64gpSF/M530Wx6Dm2e9eltSj+frr+WJdz3QXqO84dUENllFavL+gSGuT+MBzYOCsCAlKzKEj1EZ4ivkpYaNvTNrVqFpNMPsvuX3nAjlcl3g2Wmkb+hjPjTH84glNEvFsc2FYLSaU46jyb6UJ3aSUaJsCBIQfp4C6BVAYwEe9OzvuJrp8Ky4P5C0t0UvJgfdbUIh5TksTZ5QpyQiMvzpvmhJEWY+BEHHiI2a2ZRs8DPr9NZ0M6aut0AfxdM3YxIRcNU1m8lJc37/QgQETuzKCnQzZwsJF/HdVuXv+VW39kstpvRO/o5ORGaCg/SQ== cardno:13_819_971
provider:
  hetzner: true

hetzner:
  mode: hybrid
  hcloud:
    zone: eu-central
    imageName: ubuntu-24.04
    sshKeyPairName: kubeaid-cli-test
  bareMetal:
    wipeDisks: false
    sshKeyPair:
      name: kubeaid-cli-test
    installImage:
      imagePath: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz
    diskLayoutSetupCommands: |
      
      

  controlPlane:
    regions: 
      - fsn1
      - nbg1
      - hel1

    
    hcloud: 
      machineType: cax11
      replicas: 3
      loadBalancer:
        enabled: true
        region: hel1

  nodeGroups: 
    hcloud: []
    bareMetal:
      - name: general
        labels:
          node-role.kubernetes.io/general: ""
          node.cluster.x-k8s.io/nodegroup: general
        taints: []
        bareMetalHosts:
          - serverID: "2836489"
            wwns:
              - eui.002538bb31c60104
              - eui.002538bb31c600e5
          - serverID: "2836490"
            wwns:
              - eui.002538b531a43d51
              - eui.002538b531a43d50
          - serverID: "2836504"
            wwns:
              - eui.000000000000000100a075255218338c
              - eui.000000000000000100a07525521833ce
        diskLayoutSetupCommands: ""
