apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 16.1.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cluster-api-operator
  namespace: argocd
spec:
  destination:
    namespace: cluster-api-operator
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/cluster-api-operator
      targetRevision: 16.1.0
      helm:
        valueFiles:
          - $values/k8s/kubeaid-cli-test/argocd-apps/values-cluster-api-operator.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
