---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBvxbU84b4iTMrklY64aOQ+FxeucLGvocx/y1IBp/5SlBzqrolmVU/DCHkZS6MeFMlauoVjfbRXgoTpNJ7jiyA30HVoV5TZQq3rCCu3c0EBW1mFbknTFJqr3qIExRVpEj6G+56gcsKo39ofGvUwz/URS2fYH44F4kMuZ8py8XKs7WP8W5zDwg2okRZxqkzSywBuaovG//mbb3TQU2QDGNBx96WAT3sFbtRIxutpu/1uoiEfhWOyPlnf6r/QRdYxMDBqcNt5OV9FrfFa+4B2xiPV1p/INZz7E6QBK6XHq5Zqwx7208d/NQY4RxyOoUm72WykxudiZE+/DPQa7vRGvMTYnyC0G/Vco/b3I3Nc9scVz6oSi/JOSo5TPP4Z4OaJJH0CVG5Iik/M6PtxDfCWJNXjEuFkMXF9755oViqoQNdJ2IOUbZ8NA0rG3PLiWZegAyswJX2DzOAAXVe0kjy3NvPQkDkwCsm+NkPSoWwDb3UuTe90TBQuCPsGR55MZqHfIMWGbSoPx99denaTdiUCgV+RO9LmplUm1/rA4reQnNQmJSFfDYCoqV7j2OjbYSGN8fCpKS7V9EzVs3ob0Tyu2PpMr2oo89gcwGQs8AOcr36dw5w6UDQRJ1V8Rmim99O3oIRgmyRhXQtKPKAM4r5yMuhGYsTA0TYKmkeeOe5aL2rqapg2F4dqA5mk9ypY6TODyVE6trI6G5ksqZWWnTR7x0K7d9F7UELsXDHDY+V9gPRI8InNPsDlyI6+ZVxO7kfEoSjWf4D+7xN5H7At0+MaIZfW
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
