---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCVrk0oe8YOLkv1if7DTIa4vxtnFHtubwhunWvr11RRe53+o1uatrvvi7DInnSXOm6AOtczHM3aBdobKdWoOqoXcZryV5pkVfXjYrcp6bs05UpPCq2Dp23jFshVc3w2PKO9FlgypdAytcjnRR86vOd8CLJ5yeisadCDOmADXAspMCHeK7Zo9tla8HeS0jnzfwuKN9ejaNtFVM3Gg2E8qSljG0e4jxmKV6NZ6wfxjYPd+n1HnTpFILdzi1BD+ijTc8nbqf6lAymWzFJJ0t38xIrYHHoTDvoM/rbRreI7NeqsjYC7W0de8P632gVd63zq/KllaO6ye2X3GsmJsBtouicueKgYIaGlTHkx7Vc2oZAGysIaNBv/Bb8dTcYzczMhuFatGqU7i1w9Rsh0/syQucAQuAhH4I36NJYg3SxMpZ6V22PUkcxdV2gTAsFdHIMcpdjg1kUGwtw5m4pucyZdQOrmd/X7H7LXyPR7lsb5Tk22tQZvt2fJEZ2fmSrutBdPEEC2VLb9xk8LvV2+bVe0lXkJld6CykJPHGVmoIwSrTCDoVjVfuN2ukT55X70iq5YHMAmvGzb0G/wOBUUh3JtLS9Io6VgFf6VB5eppJd/t8Wdo1tcqo3pT/3H0jXBWYLHhGyomYGcxymZSvqHjSHfHMayEQxR0BM7RZILN/0xVcfme2/tmpn0Vtg+MknKSLma3FR0CdSOAWOb4k/syM+TqCV9VeU612bKW8kGF+n2y5yOngdPJ2zNwFsIHj6lyxGeMXruLA6lYkdCgT6m5LCBdldU
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
