apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 20.1.3
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Archisman-Mridha/KubeAid
      path: argocd-helm-charts/cert-manager
      targetRevision: 20.1.3
      helm:
        valueFiles:
          - $values/k8s/staging.qa.hetzner.kilroy.eu/argocd-apps/values-cert-manager.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
