apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 20.1.2
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "50"
  name: kube-prometheus
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: kubeaid
  source:
    path: k8s/staging.qa.hetzner.kilroy.eu/kube-prometheus
    repoURL: https://github.com/Archisman-Mridha/kubeaid-config
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
