apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 20.1.3
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: localpv-provisioner
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: localpv-provisioner
  project: kubeaid
  sources:
    - repoURL: https://github.com/Archisman-Mridha/KubeAid
      path: argocd-helm-charts/localpv-provisioner
      targetRevision: 20.1.3
      helm:
        valueFiles:
          - $values/k8s/staging.qa.hetzner.kilroy.eu/argocd-apps/values-localpv-provisioner.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
