apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "21.0.0"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: traefik
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: obmondo
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/traefik
      targetRevision: 21.0.0
      helm:
        valueFiles:
          - $values/k8s/staging.qa.hetzner.kilroy.eu/argocd-apps/values-obmondo-k8s-agent.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
