---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB6if+zkpQAG/f4Z1Efufaio0A0stU/pOG2Auf0WSZUcpU2ARPJCIvBc2i2O/NVEw6FKD6GgANjr7HPLgtd2vsqCqRRa/L65KqXslrS4N+WGxbB/muCT2HZm6IDJ/SMl5AwKjmFysrKDdJJ0tzU2lbAZreL1MCLzQ/fmhUaKjRNaMj3DDa0zOip+MkDNSXD8nxUv70lj8HVYpIUTf0r5Ny/ZPeqMY1riX0EdMj1hWTWCHXMVtaeY6bljVM0RJuBdVxfeqeqVYb6QrGXlklwet0Jg9Qb+SeiahR46XK0VVCGfOfw+xFdHgCmvpnGLt9VLtMPzQqz0dThaVCp0CH9mBncn/nd2nECdFsN25eI1tTpKhvXDzCdXSfAG2N5m6HpXaENOCD+qlv1gbNnGLaopO6dGkORzIiw85r1RugOvRjeUGoyQkSEt7lM9mIyB881t6ELn0zEoxwQScjLL1FOXZyVzyljGPzOuyI9rO5Nbu4lnflN3/psEpU9KK8Y+Ysffohg7SwMyFlhxBBH8IobCb77cn2uQO8cpprN0JX4uYwB5zUhchXzcs+nFldckH3mekrmcAWTyF5kjK/yKQIkbDe59/AaH06Plqf3sNnyrJDPpHOnovqk4mcEbNtDoTPV7sCSOpTyfvTeeeRcUGlvijVhQihsLTRVMVPmhJNoKtsSykgAzvY3JYNfbkg8vRpc2KMkTkz3Q7XZn/X78sOfZPbAD61hdNfw7NjSnLFOITwAatctJhu6eXvDYqMyi2VZlk9acd2oHGB5OIxgEPFAUyCH
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
