---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBMFBd/K2vUKKdUzTRkr8HYUKCNZmUm70NmufQYB+XtC3Ag13gaBNWMU1SMHAIzIzhQyVF4c87ZbftkXOLu4Nxnq4Y/xtsNZaaXd0SwFqatTCFR6LzuS2WHt8FoS9A/zL6+Iblp0Dw/7MzdcROCmRhLbrHWeTNAQ4jj1axVKja7VGEfzG6Io/jxlFX+Lkvk7Rp0Nl2DqFpWBXcgLGlG1QjjIUDi2F0PSRuUqhqYSCb5X0LWwEzAh5QcIYh4t2oQz/+9yo6+CHK9ZCsXBBYSydG1p5HrNrqZy0fD6ydbD752tg08Lz/8cSWoD8eDdN+QHbN1nEcbPwBlPCt5/78IjLM6mLu51gaJH0XjUCRHM8sKRJysHvitT8/xUXShRHXXku9wzrsn1kjVAZfrdApNfoQijcJqnoE/ymUqCZEJSsWRUp37gLgsX6Jra6/sWp0tb/MK6xx+2ndx6pZH6gvfHTXLz7NdaNeQcrsPPm3ox3ubv/CZDcsUF8A7pBQdQdsYAUN8kQ2+uroxhs4uJmfdcVK1lOyP5FN+AUiSmnRt0iFC9AaY9DSoKFJ2aTg/+wg911ueb/8HZKypDAns2/9OxIoLcLSiGC4MUp1ih2cM6aYwFMUD9CnH/hBw8mbrMMrS/fXHsD9XyE3wmayQhvI3xovL6VTLxu02KsO53x1zpwbndBrZhxLatePwT7yop3ns6dWzXgf4QXUC8qdAqWkDhrfRJ7bVKdZoeoMWH2uo8Z2SQNLasjQ+z6i/7UIPNRZwr/CoM3JzgU+rxiwgzJxcZYUI
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
