---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCAGrJqeWAs4xZ1k4va3wfDSVBw66Xy4o/U0uoNVCsY6drVWvfIo85rL60xN9aPcQG3XNX8XbWcDF9jABwSasSkK7bpwibP3Tgg8ydjuBoXekE4mQ4jmp/fK+S4FXqXxHOgYxmA7PzuuSe+YqUq9w4YwkPgmZ5r+4cn7p5towDhCOkodj0sBvOpxOrrtu/ToI7iFFLXvV2JehPUY4MXrRlqvkSP0IRziDX5+NqAEGdt1hHrGDlyO3Grkk5hcXPLRckxHVzlAjmezAXDSZAokZg3toGKzzU20nun2buGRZ0kdN3aF88FFEokDWATT66c0e9DGrMRVC8VxM04/UXqzGr3p5YDK1rEfNjhym2MErieDfwubJieZqWsn+uG1U3TFeN/YCRBMOTLnqLgR3XVdqO106DOStlnhmn7gAHXcMgDtJgpukt0oxJOyitijtUfpGC4SpDWp9myduvux1m8lUZhPL2JEZkTDYJzYLmbKV4Jp0xpmsO1xsndtSyR3gEwdMxjrIZPFDJHqdFhfYT9wY9v4Bl6c8k5H71wrNJoXc0wxNiWGKMSReoGH/lmaeZgo6Ce5MaIMwBVtLwg5Kl//jAu3HjncgwScJbqJqk9UuBnQBHt9hyY8CEH6uvgsUXK9GvcqZc1s5L2nipIMF+129onkK28cd+17FEULWigoQzyRXDHapL5J8MNXk5WzM7I8LOcva1hkje/3Qa4u+bz3B4Q+ETJhm+73nyebvnEcCXHA+UNp/xSwSudgUYY0mXJOVLnbT7Y0LkS+dGnqvVN4udM
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
