---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBCK1l7OFmh1RveqwmgCvIKWHkYcHHFiUysfWC8/GKU457leO9x+FgNdpn7KdGIokPAJmGzQb91fMlEq1/LxNDN27WTaOeK10+7nxzzQDXU6ymjDFUAtAO8so8aFmftaasNWO2fmRje3U95TqzRvTJElu0Tmj5p08lccMq+AD+8VurvQMt1iiqdxzpqbvXEzL1/tvgw77LsyJ3Vwzs/BAqpfv2rm+WAcl404UR7PBXI7ECKzTK9awoL6SxYxjmNFwN+hqlepFnRPd67HXGWiD3UuxojCxLDqg/ac8+70NRjMerqAc6AW4AxwmUtPbUsh4+FiufmVlii2pe5GqtXBtQZPOc0vHGkgcom68czoJ2ba9lSu/V4XJKn7uriiw4XSBOc60+jXRQFny/DkGbQZpM/Dj2JY5I3uKIPtk0ua6puR3V96GweFBHKxWzEDxmSTXIuRAsqllYF9PIYWAPmcM//bK73oWEaNItMP6vFOd32mQZZpCYfzzseQMd21gn8ZvvbWAjbSYUyuSAC5VD6Q73g9jRkaBztXw+F0g92UVAJxbZRQBorHdL6HCCzqGanxl6v21C+pyjEuP96UWsKrCeb0VHtt60Z/YMRjQHbyFPm2pG/Oul8H93dcCkhEqm9byrC/rF5fxSnvyXvQqTtbEp5TzsuwPFcDKK/SwZ3HmNvtYyAIMfpVa4WZ8haMwy5lWb/t0CBpa/jWvWptQ/xrJNcALGlLA+9Jfqad6Mm4LJtpoULPzUxL6dKfWwG6RdyS51SpU/F+vZYQnQ+gwOQRaVv
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
