---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgAG8tHd04Kxo9R4SsS4VPY8ej2kuhc54aMU9G1ZitW+XDE/VnLBWYinkNfL7HSAqlE2RKk2nNDKvFcjYEWnLQjUE8YoJ+FZP7jBctg4slSVeHztVwIdoDhXhX35kyQuQMp8ZYnRStseSbIjUNAuK2E73o9CfrjdBoEA33yNndUqQpQRlVWL++epNOvsQeEY7InxDh6EPG7MUgInN9riLqJQSsZoku7lbRifR+W6UQuhQJeFfhB6m00SFxjEPnF5NHwKDPmDTPU0mIv+2qsW9ZJ3kd+Q2B2tT2biCaOr7isEyb4aw0Gl9ZyueG8avhIvlUtgOL9MibnjT5ByvUNCQuZjpklKrZC6dhfoqvZ9ey3ALIi5L6F28DV8EFd3tAhVkoZA35DDMPiiKiH/bQf4jbhiPkwp2oHix7sDPurOv0PedEDc8darytXtq3121Rxs2BV2HzokglTcM4yJfrPx5OuDTcIEUmgYeLEYo1apkX99bobN8tKPxnm66Dp8LzCyQ9CKRqM4LaMptClKSyoHcupIN8pVFO8MJiAjZwnx99uSqzsxmuRgOrSJXRAnKIgxaZ8cyy/Az4oiE7fF5vpcIxMFuep9p9Twub9GPNQ0ip6KKOoEj10W56PZxjj8E4x5cQMu7AS3aQPBr1ysyKbLmcxbEmKkmjzVFQlNa36BEUJBD+V88FZaQSAY9XIoxdd3naU1C0YOp9NiyNDUPB2y/0Xc6ZscNHoJg4zYwokscIBAtj6y6m4ERyW9FpsIQwRO25TF16JpGZ0Idhu/YgFzvgB8
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
