---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCJ3oSn5EZov8vO+DRwIWxCA1wl3G9yvj0QRvKSEfzRhBH9DZYQQdofGKR0Faf54Vmvt8RBxpsby2EGTEEwNyBCKcplu+0UP2+sWuY/JpFMZkjF/qqLJtQMsh71bdCSpi9XLaqjCswYGT2EtQSX/MWnK4eITgOM9J3COvo8++WIX2QNeZnD07+svCiUQLJMwAqPtMA2NJ5a0J6rrDLi1LoJq552d/DBnNqJWSp8LbFIWVuG+VaeuYkSijzs7I9onW9DyF/eUsJhyDEcHvs+1DaRtNmJC8xGSvN8I+tmMPuSE9hz6HCf+T6DwWd7BhEmdSQvmTM8u2LwX9UHDeVrO5JCHkOZYVSaCmMwIyFSTwnMoDH2yxOXWKL2CzNJt9ArOstsCXCwU9i2lnUK4hz8ogPFlX8eMjuK/YttqSuHanbzPKwJ2FMDYlWn/RJt45+gzVnRGU4uWJqtnGmMJANsDM9wcnKPh0uMSLcXdWn8+JhDNqa5vlMDpPhHTEduB0CUVGKxBO8ldmYWTyYS81vCtp5Dmqsg1zdT3m/b/Yg7YALqiJKA/hxpIMqe5WrohTuAclAVIy6FodtGWwDDVCOoqLqy8SJv4zeZ4j77yCn6mN/nEswzUtjRJkBFc3pq3yTRcFNGfjIOrRp2GN7J6zpYWLJ8I+bWW262k7R4EbTbni0tjzt/aZrVQ+w4Mc6udVR49ueD0BBVIljkviVZ+UaUNkM6cvguZ0hfqeAcGGMF22vntcLWHR6clNhfUxJQe/aMxacT6BOLFSK6EnPfufTnsamJ
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
