---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBDweyS0PaK4modiiF4MQOXvn0pI/qDvQjtdlGX8S6BO77OWmtuGbArY9ZZf+aaIKMuz9FIioRrbdu38mRTPhBfJsr0ovXRoxnHUOe8+1XHI1CD9esjqAp1IHG7GrB4TuM8vCq+7WkPENJrbO0KUpq0DS02uS0Il3gishKRJb34HgdkA7Smz+ZaaKbVgMxOgL+RsvTfC2+bCi12kuh7rhCUsbjnnHqvx2CSbzGeDLaBgbQ45EQ5+iavrepZCGbvpT3tntikfrMKlKtam+sMp6jpkdLS0RDTqofzmiqUJqCcjoNjt/VIqiXzlDAZQegqJwMwHwT0PEPa28pr1jrBPbcM3nxyW4NUr5z4/zFhk7w13+TSEpmrbx7wk4n9SOKdH8vpgurA6xVi4LibAljFNsLXYeZsScBlUPAWfG0BiHZ+6u7Y1LFmAgtb3sUXOSqnNxJpsyksHeB5bFY+JTYFJoWXxU+HsHZGtpp1AEt2lEy+bPE6UgswkTb7FlabHh5wD8k425oPNTnyvcUUROKnxap6flRGlSd7O35jK4wY3/+mg0sOYkR2rmPEEgHLFdt8i0T4+UqEPi+L7TlL86bKt126rrinwwI47GoYuHU647W1ge8p6puqmTEHrscI8OmTSXEVddmckvJBZdTVsmuZx/vIQ2man9pxfx1+Xq/g3B7RIVgOFaZwUG2So++K5nh1qR5eh5nIryHxWppRidt+LsTeSBRcnN04Y6TtWSDwhEJWpZB3xLIxL4jCo7hHIo5H1gTkAN9Bj7jIMIQa3Sd9umOV
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
