---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCRoL4hPHIKlY/qSC7j+UhwxEhw4X4881z2Md4rElyTGEXVEk2XAG2Y/bD5gbie+X5Rn6rWA/A213N5LladYgOs+hm/m6q3/AxmJHHDu6UgJp3AkxbE7FuJdzVBmpcFdpbxcvxOv9JA06yrzSuTOqUebeSDRoAJjL2F7uWIddkv5mKRIUn8nknIU6OZVB7tmUOPLxt2EuZpO+cpPe26CWeI49SHHESM1bdd+sTBEcjo/ooOiS6cr62OC3uoKaXOyCGXawnL0L63FbOc+ekgd3gj0HKX8j4QlfqWPJrQBRhc+c+utGihcJGMS7hh1y98a75xl5gO5RUelu6IfsaaK1HGVefOBNPMwkOxKEcwACev1cCu+36UVyhQcBVEce2qiq+Ywb2HDB1naPSW+Kk0DQf3ky2BDVu5uYebhUPtpSsTpWLZGsqULi3qVM6PF2oyMM1GdcDlqWbZ6E/avFzFJA03Yolr3zxFdK2Bw/tCnDcSl8iYbKx8Jp0VmKA8LTBczwwsfU+gg6EX2+xY2PHk6Yppixj40uBHPWCpy143eTGRbucHKrcwjjIb9CIcy720+VrLykp+zmq4FgRQC0ufYLsqbdLhj57pYt4jSVtUuEz36jzTJ+syvy8q7WexN7jNiMtoGeh63fvNwtFND4TVP1J6mw//xKBXf9SEaF/B2cEGOL+4Zw0w1N/VCbL87CRiNYO9Krj/m0eIvtwsY1QhEDjaTGT/xmiPX7i4JgFm4yF3W471z6BLxAB9guBITUm4igD0YGJgvfweUAYSBEAryjhN
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
