---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBs8psAf4fpjmtL/h34Ant7Rj8aG9nJjW2a6arCaCSDtPuiQycGOgzEfiJvEPjKnYN/YD42ev6uvOSnbvm9ZFZ6gO2oDSicDBEWdVpY0LuZChb7m0wQjSrDqfvl9x7LD8b/uIcl92kH8p14OgfjuuFxq8Wtj3J7KCAn3FXpxhUQ9drHBFuCx/F3r2cRnP6DaWjgcpWdSYfNrm5JUC2yKWiZRihyd1HK7k/hEk1n0v6KFNnWufaj8MF+bV6SfLClPouydYIgV7kG5FDnHpLM0OK58SpAwX2GPhHPdbBOLIhA9kqA28dfX6abLBMkz+cAppDOIJ+nTUeSDQE0B3qqLvZ2cj9V0HYBoELP9KWz8TRMyFWQPHtMGHhECq99FCl57VFiAwZNjipGZmMiPoHjWtsoNBRPOj/UAtYjsdFhdqJogVEtoygeE1xZr53SVkCUGIGLsv9OoEoUK+Y67KK7crWwmRQI2OPY8RQwO/n5NY4Etia/IxACzdXU5hJzJMw8tdm2RvMguvKHHQ65CZ0rBVHhlliJGrtsjLjPmBHbCy/LMn/HGoaBjhdRUjtPC0mGjTcqPtqNiOYwW+R1BDZAsrhg0cOgAQlmVuPvnexHttcBXkJLKUBQ1haJPG2G45qGkwy1aKK2XBtzBkVVOT1uvwqwzKmzjvadZcsU9IBFIer/R//pIRgzPukZo4ITJHmeW7qWCHQQ4EU1znTcb7JWrK6gCPrB++W0W0Y3nQT7UAVHOZalF6+6Pj0vIxWKJzsiOrT9x9JF/AieXe0ZzULj/+UD
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
