---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgA7U5PFjwLdJaW94ihK1fM716wxdQZE0fXVl0OlJ0zDSn+fJ694dlaLXaEbG45nl94clWDhhJoxeNypxEyqKSqHt8EJg9bfe7tr7DWIVCLeKLzCXZ1im1Eubmvs7QqpQNE98rdtWpzxI40aSTcDitG/qa+kCMyUha8pVZ9pHdhY60URNF4qxYOmIkoIyKMfjBsBe10MIopt9bBU6H7eXo5Z8758mXKVxbExyMW5AtIaTGKxpG796MdF60vexiWK94r/j4OlDk60aG/PDRu68rscDbiWL5cBslIZqwUBIkDuuqcuHm0FoS1Tg+SGB5TIKsEPkzAvt6Ex4C68v5SH1ZkeGg5InM/QQ3YPztf5drG1m4cle3Cm8SshH8/OSW6KQkRU1SzskwfS8D6F1E+fDV014eQJzcNYd5seYdGQ5/ayF5xPkTRbQnIn0YunHipFmcDF+2ZsCNrU9ZtSHIy7bOgTz53qVJoZaUTXK5jvEtpFyl0nAXtphuM0pxgVYnSoDagBSyrfvtmjthTS5fcT8tkB6vdKPcag3zNpJelycjmMREGVLbKb30vhObhQhhqbDiTuEINoK3Ous4pvxaheKIL2PtTnF/taGLexujwa4U+2GHV9Q/EGuMSOnjGr9NnQk6Z1P++c1Twjx5NvDjkUXwu2mgf1lCMqUW/pvootrbDnPGEZjGAt5XdGq1/Sll7Z/GHK5MWjWAZUpfbUYJNc9bQ96LrlfDy32elezibhqT5Y8YRLPfdbIKvNCxbN0UYQa7paxQRdB26cqpJPtSK7kp6V
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
