---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCvlEwOSi/tOpkixn/dY/FCkrn6W1MyLt3z0nBuxP6nSdgxv7pUri5vqHHDzAraOGTy69poC98mCVroYNNahZmTkxoQkuJBbCyz7WLzKMMSkxPJ6NfGAJ0Aim4iOereLwCxUmfsc0xq5YEbaC05cRMrLuhjGAGWRkO1zuTCtNx+mwcpQdc+ZAgcGQxgtqGvf3PsQ53pIdeLSDFDyBqdb7JDqqyA2el4DPvuSRcPRaqjYhq3bgG9p8zOcWLyQrakMvZXbYEc4+nD/pqfzYHnNFI7zCrWO+U6gteVSkVWoTSOKPAHsdzqGlOTr8h/thhiez6r/YJwRFhx4pvKhr3nJkPyW6c6K6YcHYjg6Fvw7uvvgbiOP7ZtVhe1BuG/wtPIMm0nf1NdD+YEENhplel+hyHJ7hta7gnoGI3xKgs4QIJmRr21qYQdxOJ5CdIVZiACjVqPBAb7wus3h+eDvwJdrJLgwzkN/WlVVYziAZ3VQKETQWDAevvAsOD0Hwr/Wu1xbqc/YUqSjRry24guL89YjXFN86cL1dRHjSYOFibVEanrenqnbNDA05/TZBvbJsDEDKvsePV37eY5Dk8xEOSeaYw9dH8+hmWYgOGH/ULsK8P6HAN0h1Fv3ZvU3brm9uTA2SZyJAUmoBVxVKuaANMAqACGmkmSQ4v/iENIp85YbkZwfZJkFKuO4/j41Ppt+Po1MOBgEmE0ieTdII73PMIXk6yV3FU9FMP5RtHszq1VSaf7oVS5hKe6yeIJapwmeCC+MJkWLTLFfL5KD5w9pKU+u8d9
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
