---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgARE5/GtM/+bqyQ3RFqW5h3Jt0vkvkaJUMj4o6dDosVF14I2MkBuG1OTOSwF4tJdvHokKrb9O9Yh/D2Wd9vmLXzou+lj5btALUBRNLzUvnQWzBTxkchIckgr/8pwJMFqSmAw0Zp5WcFbPSvRpYfiPwK6ptGQxZMxjNkxPnRJ/o4THmJyAWY1R5kmqTkD9AEOHVxMNJ/8ijnSlP+aPZqGsUG+uMbZCNso4EZKbI+qn16sLwG3rgYLcx4wuc8O/rlG50nOjTsek9n4oOQ+CwZvO0rvfO5ftMVkeJ1FbhpLh1vJ8k2jquF5HPr2JRdpkmy+VxTq5TLY0dPxkPWiDOaNbBJLyaIyKToOWIdNwp0u3qwZYt6pWU9vNJOejBSVA19wgqWauOb6RepWm8tqs5nU3jwYoyLqjZHtT1eZh0hnfEWRBe6mmTS/UHIzloGffsOuo6rvKxACQsBp81k2dSjFXepud0SFL9CWX8W1t7k0c44ltV16u9M6psHz41PgrEYQe2R5N8lzcXQ+pqxkHjBJ1hECasp6xsrSYxMZcMigXxhs3D0BAK8YWYyocdi4DETac0VqcGt15kQySt/Yenzkj9OAxfN++oIzoXCm6PsMSHhJi7LnZSxgY+WjujCYjHtr3cGOvUVmcoiD6p0L6rJ1Wtv9SGLmrrxPnW9U9tk/9b+N3MMN8gj2lMv3k/kmTddLR47Vk3ssG76fzo4EBKg/g8d+h1I6ItMBuw1lno9fUbWdlhDNKY8WT2wzoFZ8qQ+hazU7P7k4pPsbB2iEcZpjXro
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
