---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCBSbYGmjVa6DaPzr0hjy3sZqxXNItVvjvUab2FdrJ3MLJv5c4PuQiynbTq8dwHUCIiNlgubA7p6S2N8hPQOKTMpHp0kmhRhmEyZjaIlO0+caOajVZ3ceC8K5TKlBP3P+t9rEoGWd6z4ohpQ+hwIx81FHOPerOkBwVIQl/adetH5vI5kkSeKLYTwXYVjSec8qrzRkEbGRYqfX1jLm0TvWuuclUb/zoaZJiOE64Oauk9d7Y55SJ+orA1SuJSdenYc3nqylQ59l6fwd2G8OV1nKXprBOFOIGJTSq6bAdKEwpYpCJlwhzn8dOndbUrDZwR7KNiDELFVkxUaqrNRNE9DWUtRVfd+i/j1Pkawf1UHc87U0yqxrN6Mp98PjyYWF1VY4eBiDqrYKPmWXv8hnOMRTX5qulg1NKAF2iZ0LvgbBJ2QqGY9cYQGrfsNQrp0GhfW9+DPHiS09741Ptb+sZqhbpes7qFj5UW41GbS6aiYVtA/DY7BZXgCNiBXR6iowwrj+9eVwNQE0Y8MNQR9oCK9W6VIIgFk+P8/Vzpxx0yr2psJv1mx8z4cClaQH8Wyx4ZsWB2eLxb81upsvrKzCYl0zuB4TpYKeB4e5mu+DpnP+G3QXZhZCkIPZSZW51nRx1DaKKmlqRK4s4G2xTiVQfLVOn//Y2Qwqr34j5y5eESvnooarac/L8lCsroFkMpzBPfiTaIy/QLpVv6cZcG5S5fuYV/pXMSOzt8QGer6fw7hm6H6ftVCDkU1L/5QSCFQPTx6eG3GlHytjzfTRszK9xhDs8C
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
