---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgC6bJVZEBr6tw3uIzYbbgKXMR1yzk/uh3ymtg486P6ID9egl8xrKO9WCSY1u3pfsip7SBFSgoLlcpYZLSP03mZY8NVo7AI3fClj3l22E+O4I+LrgpY4OZXTzLZ2sASAaBe2zL5j9mXT1lXYrAVoczFIX1gLWKiie9VNWcgYqbLItBhn8TohmDFnSz3U4U6qucAmZn2Z5Bt76Mkthdnv25qahOlXyqWBYOIEN+ROi/Bl30BpbSiirCkOgtaqwviWXtP6sJF3ZKzJ/yJbj2lG+/9XKaG2/2zqfBH6Zl4/CN3DiP4pclJD4u+yMtdUTNVj/Ag1D6J6xwMS6fww67WLshBgRnaVECPp86P2zBo471mSGF+isPCnk9CU+bmNTllLY8qGt1n5QSWkWni0cUhQwNAHkK9U2ckmw2G2qCZZ7D3ijXyVtc4F75n/Xb62mMuEJTnY689TQLXxUuTpn2MX2iUULKpy6JA5SFlwsCcwRKqJSLTuT6zaHWllAJteDdRnnxfDkM0d2qARCqwFHRNhDvMk02zszURplSDwNNUAGyc9pxIGTGyqwsT2zQ+dDSzglJwy6bOnzWsEqgTeETDbbkvMlnq3U7rXXs/zINAuLLjxoriB9ajNQ3hGgBjiXfnpBsdDQ6nZOn8rgkgx3zsvikCoIOKkC1O+7UrYR6UZiJ19NM+/tERpeVhZfyrWYfrPeQ/+pkB3bpgGFhtrSi+IqYk700oyjBaekdDKCefg8+0XKd2tzV89Ot06Ve8jOMdueW4LpVcfdJbK9sjvD1yri5zr
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
