---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB0JwtvyRGxwvEVi3KeyW9euZgW1YFaDL0YiT4NAkS9YlkuHs5oRyzW/0xIxyRU79DobJQUjmDRqlsqpadfuapNVAEYDyhLJ1Z2luj8s4rtTU4sHx6Fh4b/9eTgd5b8vv6juvaxwaz+/tzEABHQuPg0zhzyw+FqlsGOr0LBbS10wruBwnqW9D6K83M4VDSg4pEG0T+Cs4ooG5qAhVFHEgjR0f/P3ORyNFSWy2dO5lgvvSj+7FTobrNaEifBSuT+xg/fY6C2A/amiRe3BH/Y1KOGQ8w6u2zgdXAfd/RIcIpyVSo3b6M+LDOffFtpj/nOXRMWA0JWgl6ajrnd5mcFK86KQvVH6XgshpE5Jm2qV/ioNwEM2iRJt9lu1mnRSNFfRDCxUxKNW5vh39t0/n8u4ZkkQq22lAz5XcVZHvBZocaWFkKD0NS/r5/HnmzgRgaetqWKzGL0YrVF22bf+aGWXyacAmmn8UMDlYfN68oUhnbUnFBk5H+SB5ChbS2vl6rSszsmj4X+g+osbvptQmSMFf7+q51GNAp+0GhN2Pvqkbi0MI2sMHGrEemVPpnsagjzuRVohHMuPsd6WPBoJFURmF7FlCrWszQCw4yNkr80kJt7TuMCFb26lE1LwrYZyzUuBy+CVJFJ2YYZbx0PuAz6FkHG4x2wGtAVlNkKAQENqrPtVHTLsWj+8RzLIxX/8Os5PvZaCec5mgT/NLZrt46NOc7OHZ1ZjehG6+VTX4/baPnZtFbbxG5gi2MLYrmAg4my0UE+6h6ar81UCacfnaXSCD3D
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
