---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBEsfKlW/oDrIczZ6LaZdo1mr2nAZkQcyyON6nOHc92p94pL9CeLLQBH1deUn1rer8FeFZqgEA85ZDJHswXmyCj605Fspuz6M/Rg4l00z2vAkVxuEarS37EiNSQM1H5kEu90tSxmcdLhuI9jMBWeqtInBh9wP9ZzXHI/op29TAwNvBDuwyiJDjY6Lo8F7cxyNKsDrURnEml4/kXIYVIqDT7R8BDk8ffsFNyEsrzrOodUfNJSaZuXwqoIiI+7g3meIWdAciK63yrF81xoOor7qokonRY+9Dvp/9m5Q5yl7X1iqOUVPJxfO2iifkfuip3opKakETRQJuSrwny2WaHOmScJLBrYghu+Us6MIC5GgI0SEFg745+YzLYN63nubqGRCzXMxg/1mQ2aQPWekXGWgpv2vlnGZkzfhpUZyGXtNKWCfBQdJMfKNNUtYm0Wvw9TU0HEJYMlv/DT9Zfb10JP14D4NNkO3OeWzVz7dIPxS8eUDYXSJK53LC+Ey/78o5Eu9hjWVRgXpMBMnklH2ORn0u7ugADaI+1CcLJaYfI/voj44vMhKeJ5Xjq8nmywPG2fpNf9m2zZ6WHzMSaQrVZzjmO+vIECsAHJVlBhENCo2ZR0qTnxO8mbkfyQFKldef/YsfEbmEDiJ6KD7L/9mJR764s34E660GGr4UHCdLQIGEBd3ZMdmdug99gn6ZEeZary+7UStrIQdDA7stJ5sbRq5WI+6yIJnktlRmQa00XAttj6+OW27hZvWeQ6chviq325OR9LWXsNU9MfPt9m3BWyKaH
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
