---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloakx
spec:
  encryptedData:
    KEYCLOAK_PASSWORD: AgBoI1sS2gNaeSeSWB9vWysOW0yZ/G3aW7PW8ep5xmxzfiRLWRnQt59l8aZGrXngYEHg5CRhLg62KpZjLXqmLtTF2doZmYX3gNkrY85W2jWnRsLGugZaDLGPN79dylItSX+fj6VB8OYoaJJlOmBoue2+DSnG2qxFzukOXqRJAkQq6rCcuBdoWZHo/8JODUs6oWMm7TMUNQJXNZafR2kXtty5/IW1Q6Z0xyX9K5be6Rf8cTL+FxkmxfhRtT5W84gEBR8mC2wLa88ghRtHdLU5ybi8zrCAfgySo65M4HcTUfBQW49C/XaypC2rLZfVDSjbVHULWQn32C9PiqRJnVlshcZOgW9Xv9tKWDheC+ge9Zg/+MGJHPsIjQtw83sDFZj4d6Q7QSJIpxMsad5y3MNFB+JaEUzH4RaUBDw6wkDOuhzXpv982YdTMsDGTDETsOAUkm43wbOYNkPC6N/QoBfQ5GarV+rCgnQnSnjeMjy7uPogxlaY835W5uGKoT1IhDaj2aru1EhKe+eu+A4eKvXY23UXedN6uQQXzrtw2/748kzvZjjTDDpNm12nDbbloQF67WvYVG5CreDLkIEJci7EeihXIIrBwUirmB4iJaGeSVaPRfAimTZr3J37LznDny+mausjXZRzhgVHL81TzucZ2io96a5L112WlFcBJfLeMvDUmuNkTbZgT1p/2n6Xm8N2gd1EjIhMu045UttmseH5Jw9J
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloakx
    type: Opaque
