---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloakx
spec:
  encryptedData:
    KEYCLOAK_PASSWORD: AgB7ZkJEbMN3Zv2sdWXo3swjc+kXX7ecotY5kFzoqFDUVqQ3RlQcFFD0g2J65aPEnKQSlBx+QHP73XBLNVV6VycZLuwwX3mZz+ox270Tcwa2pzdQzo7W/ElgKcTnbaRo6chOyeXlqidUf4WwMjPVb4vih92i6ERLD4xpDlaewZNEsx/CBJQzv96Khu8ERurWzgAcVNu3aGcPj7Y2utVFoth7Vydx16l4pqkOFAM26ZlNa+oIo/4mYg4GIWXd9KkIRUwg6z0MPnxVCADqzaB8n6r6wG49r6fLeXt09Lbpno6VwKMDewz17Bkispeybw/BG8nAGwjtSHGlZzdBIpvDwy6Vpqt2u8Z4TRCzVVhqKJUS7VWo4vqeqzwDan1PPil0YlVb1z1dkQc78bBRu9OpvF3v0Kk0z9CYKsG0XU50FB++iWbWRb31JyarVVTciYx2D/mZl3XdDWVlNg5pKitJWmn2v5fJX8mqeVSCgnHz+mXm54XSMji5eT0x5KWA3NjegIXzSgSJ0YEEaKEhYgETFXM3yTTxMpNmCcS5Q/tYDqNOOCa8hkWyj18hxK9xCc4nbTNDh4lCsWKfDHxSIA54W8txgIfYjS96LaisbJ9hJfhvWNirS+kxd3j/8hq2/A+4CvXdflNX4SKrqIfHwjNxCUnbUQZMASlH8yRR+FBqqYJyPMD9ffIF6/9SOMCjMNgVdPZ5/4cAiKD90VIHWvbT1j0W
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloakx
    type: Opaque
