---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloakx
spec:
  encryptedData:
    KEYCLOAK_PASSWORD: AgBhApbEkS0kKBSQauF3abF/EaM2GzKRgzZmygc5Vwgt3ARhLiHxidjWep9Nd557uQDM0rMeeWLQ7MqjfgIomk1RQggeUFUKDCu05itCkW6Jd4HA/2xSdN7BJ16OFPUZ+uHVY1dJLRanE0Lh4DCYassFGOGgt+gSNpvJ/Gu1mp+054zKBOdMrUMbjWZS8SmMFux60nryb//lidyy7ryCVQOthQ8E+BCRvwDjLDav/HmPLCsjPvi4guDNIduPzi/lw2XPguTLTzoqXcLSCmcH3uu97Q2uILxGxPmzZS/dhhLO2/k7uENjjRC3PIEdOojqUEetuG9i+IxkkYz0RbWvyOGCjUNUGyvzId0scmBOrUZJ9Z8jZBxldy+5e7XsCzbYW+IB7/r4JB+2o2RgiFCSCEDQAEC4GrFId5HKkzy43S8+k7bzjWAWB/AnZcQQ/ZBLkszP0pT8KjNEKuBEo4m9XULARCNh8o8bB7GiDhnAs83byFwzb3gmtULEGbY2pcmhNYNpSuLI1zqB2seAToMAN1bJlhjUqUayeyxKyb/nxEJZcO4WyiQkcKDMufqIpGOEva3h5kNKWRJ2YpHejlMTmFzVtsmuMSECUajIeqsJZ5F/y9sHMveHpOw2g3cg08wsKATUZpGON/RNBeho/kQ6HIhjq4cYdJyekCf38cH4RpVSwilmuLosxXKL7l4CpQLBjto207uVUxE2/xMtYtBPdRyH
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloakx
    type: Opaque
