apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 21.0.0
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid
      path: argocd-helm-charts/cert-manager
      targetRevision: 21.0.0
      helm:
        valueFiles:
          - $values/k8s/vpn-obmondo/argocd-apps/values-cert-manager.yaml
    - repoURL: https://gitea.obmondo.com/EnableIT/kubeaid-config-enableit
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
