---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCnxkM8YADlvYq8Xpjuri+NQJg78PBUvecRAKsnPvM1CuuCnUfr3wjEKJk/D/smGNw5kpYL9fMudU2L3N4P//RipI2geX8ovIcofLKMUQg3w5PH7ibHaAndae1VjKD6m/BRIMu+hpq9nJ/Xncws4fnn9fJH/k0u7Na+8NrJZs2K7VcbSNY3kSovu9v1R7szGbiWb8azojBX5HrOm6dkDuT9JPceFVGnga9DuYJplsyUobWo5jC1akDobVaB1jp+RLCJBiSJmedXGIr6dZZhxegqzir87KPEyrvHqxiMQ0ie382kFSU+ZoJPjTKdpJYEF4Ly5sgResS3ZjRzRXrNGYZCBCGeIeci5yFtA+RpslBHozw7xuuwpFitBJ96/eOgc/Nsxxb//3QxTe7p0jURDhd2ZJacP1I/UhhiRGI9HFqw0glF5GvLvvdyEyTeLihWQhl5Gu8pWs9GOcIKUnd0drggJGISrOr9+Y2atjZV3mSBQMTwV8q6/V8F6QfsSzHANnF2PZQf1tb0gcRX5LyQum9u02wqZLXTP1n0Jl1aaoNxR5nRsVlmbmagLH2AOk7KWLz3pnEAUgygu2PniDwt2ayDdU+cSa8itNCvcthrlWKW71lOR4orMXOzmccxkEP9YWWiwx0JrqRuKUk2vIys5teVepWHvl/E49Vv2InI85hMh//dvYSJoJBXUwlmlOd/3uvAyCbJUdCeedFbJCs5/uH9VVytaWUZyfdINGx1ATPs3QkdMCwnUF55
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
