---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA4uBHWADab33nZFlZ+YFv0OAL3kwt+wMe8zi8sqtsrcc7XqIvfBwPglTVNwn6UfhcCKZwc1vxdT0uDN1fIqVl6fH7v8l3kvUK+yZWsB3oYZbYLyrslQvF+FDcPb8IYAjolW7ETK9Dk6Zj1fl2K8scKr3+wfC4ZeLHXjH65bf3HZVbx75UktF6V5KFW2aCtWFmBOgNBdQc9UsepSSmaEo3JjPnpYIBv9IRUaPjOLT0Wiq58cNqwcCfFArBjzRFLtjS6vh71EBk9nYFRUWjE3xpo7RoKlQdPHMGSMPw7ZVvKZ+abpdVyl2uuMkJC8bN9EvqDPjDYQB3E3tFZLIoTVKnt7O1Qog7oP6gNadkd7Hunzs9fQkUBO5X09TBszlrBjoMTlG3M62ToUkoq9fijdqnpRwFhdM1qvutMNNkBGgT0OHdnVFA3tWu7Z3jzFtbaa3RmLO2TV+vAWS5CSTlHqQ2ooHzxA0DDS0mmDqNskmWb37sm7pmgCj3k068b8JK83CRL9wj6p9ccQ3MPM4JDxqZVyVo7POpxFUgia1vn1JtmhMyQnS7yznh4+8MVOkQs6Zp5Rk9EaHiq62y9P2fPZ3dbgbKKvMKwYIV1EL8TG5chivAgfwIobraRotcmTQ48iXA2RpoQ3ci1U+rMp+aUi4rJAW661BCZ9NoDDOFvRFbW0mjAm75a9vG9M+r5BJX0E68cdvVa9ejo99niigenwjgBOtxiNbdeHPT8S84tFWuMM2byZFCfLF1Q
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
