---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAIjOeDY0GzM0oa5TqcXQCedCTcgwW+iP1uRpOokwFOZzohsqY2Jycd0Cd0SQ9B90zMOA1elCOtjl5kxRlH3otHkw6E0ebA8HBIKhYyWb5cRZGiEumnW6VfpotfJKWCnRu6bR1XWzkpSVQPG7F+ZhRt487BP+4TS8k+Hr6Lt2bSiyPPVPbAMmxNtsolZv7Q50A5hM7gEBK9DsG4AoM1Afvm2vT/SMxnZIt2jGEkkdA5IfJ6j49PjouxqYfzb5R4ck4oI8X96Xddjd6L1BKX4tfO76pIFm3jaaOE+OThYUEbyVjIdEFziYveBpmbRNUuAKPvzsB/B/3L1coMefkY/mnzwMF+x2MGzVeZzxpbJYU+xgM34Vy6+KidyLo07pgMsf6jyYG2cPhVU8Ln7N/EDddI70qrFnIGE9SkEDdtFnLMMUJRGIfisiGapuTiP/A+6Emc7j/IdcEwaSuF9blnycwUD6B6wPaXj4AB/La+hGLlRrtPAhelxorpLTfSnoqtzMHFIGwYHe1ZdL8L9hujrvuHAfh3ODKdOXnPdKEfiqPR96Fi1PzbWoBPCTxHV/KzTCNahHXHlKNqxeZktUvj6Byjccwlf61mfuKJA7ZZSXK5Kwx8a20GnVUJEQqH9DQh18otRSxQKSlNyVlZYB52lMW8fr5aQ/SLGTJGzqMBQb7V4b6WnDvXguhdOtAyrI+CbxBlqsQCJuaEw54iGAZ1MCWVnvVSsPNLj69imjh12JA8o2pCRbhsSTUL
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
