---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCcwGapPMxU9eStwBvY8fdjvQj1DWq/rFtvET4j4F+QcvxXuW6zohw7uCzZjhGsO1pe+2591/Jm0YAiEPXJFkiKVd+Lc1auU4ByHN2JtULEsyGChPyz3lt7F0PloTehXvH/G7mxEjOtzPME7yJ15apqqqI5IPqkUHLkQTwf/Zsjgx9si4Po/a+VddmuwIrjLGPyyg6jkIY+cf33uqbMSilr2gFPvGMitKlxGVNe2O/7TuhSDzWwOU9Y1dxLjnf6UHzQsvUchIn7iy3vEskEYag7JlE6OflJUbJDiIr67QXV9Gg0G8U5oslNVAGe4zTYOtZjv2VPrwbv+rPIhkWrQSPiRaq1D6RobpuswLbu7Y8tEuD5alw1qhjgo4NCrjvgAdLAmFJzaUunCoWSXkIfnwScdOmDWWThUu+mXksU6T1Gxj1XqWncNX1iSf1MoHlEEOmHZkQn0hOi2VCAanxRCYmFeWozx6cjI1SY34bz+I7j+nlYiSWeZoMvR+luBt/FHbEthFrqsfPy4oYRNVtplkhzzmA8Bph36xtsrYS0QnQ7E7/s2yEcpY+2bBsmVZTYtUzkYdOF2iJ3BFohnxF/oauou594jdOXAttvyNdNpbzL7F1ejaWxzi8LOHlmTIanIrjf8YRNN4x4jLpVYorjgW427NrNGPJmSbgfCz6KajzVWHND0APZ/PMTQH+lo4dVnU4Ud+yBVAcuN1dYtlI+qVnD9fI19CgbzKR2aUSYwSNihrG0Jj5MU6tf
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
