---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCeGHn9N/bZe0egpingTGp7asMWJxc8+nesjARe5Zq+PTYYEa2b0UpKoRRo/4cJK9OO+lEtpmLxjiNdRZUo1A9TVsknlrMqTUsDWvTQF/ytqPd/UZeJV6dHe68EBJSGK/ijlyUGM5bDEfVykTj6PoZTr7R/IdpI4n1aEj0384RBLC72f77rTQLEt/vLKTypHU5u8ny2ElHvzF6fEwOFT0pHs+35s9fPJGdQ6YYAA158mawbJzlgRYeorS5O/YneFnNuU3t3ydlg2uvo07wbNLoFxsriXSLPMJsGi1Yuxh9IUyPs0s3f1/djDYq9R6vq8DDKxuilDaNzXy1Y75ss/K22tdeOQT+xNE9fOwI4Z7Gr5Ow9lI6KksVGqLBO+RVZjZkedJpHpWXHthlYeBhs/Oyzl9VvLBUt8Zxerq6CpUoa54CYLnprPbm3h0kswlWw22F8tF/KwZi3NiwGqHl1qG/X8VwlPA7HIXpK5A2hkfPOubOhTALQjbRAbp4vVlarjvwfZGhfM71noeZT0i+NaJxpvbzmxmxkxPfCMUZIdRkDOB3gDZUMP84jTD75oyRK7nm/ZZw4NwT1fHq11FjS4sIcV9lpk52h3XcsaG8dRgi/ehbj+kEnA1pQt6JUaqtoGRPGRUyrcfdrIhInVoaKU/foQWdrxtitphxwschTd83Uhr0v+Dgiv2zB20xJQRj7An/pDaMyeYJSxRtQp1eJaVBWMDqp2dG0pb6v4amM1JcEyPX0AyhceCL6
  template:
    metadata:
      name: cloudflare-credentials
      namespace: external-dns
    type: Opaque
