---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgASKC6PR+C8VP+vGgq799nH1hbNjIBoQ40LnL9iptsWX9IJjUxi/dANHA5LJODA62l/DDYqCcaCy0tuBKXrfXbpnuOVNvta5xm6vvUD2EMGrpBpHIIZ5oXDu3fJ5olYrjgoe85mrswAPTiO2+ck+nntK8a/4UyCKs3TeeXGOWJw3DkFOF4WXINZuHYJpmp9Z0f/wP8GHU/texewAHLNLejR94UgJ2FlS1tZMW6X2ewRB4EzWogtHSklBqX/SFmIGcwJSQNDLwoFv7FOhix1d7pjnVVnus2lA+9zVgNAeW/GPa/MRnwdr0koCYSWNEvo0YtWjIMZpeaMqJSK/X3erX70V+sOc5/uUkAfz/+CsAxSFkHHizyJ3yPy6lGP+L0bn6JM/pnFfangirLE1s9yhdIyge8zlH+R+luTlArT7tYL8Q94c7GMzTcjPmtA9LDqzptdDpainDYykMbHYtGp9eJ1D9bjpmr795n6OvbN40xdt/ESpnXP634cuIwv8GVxMMP2RUF2QICeB4Qtu14WHmlrGdC36JGnv3Pp2mKxoYQDwn9AtiKeHgVHWHA64WM3Br4PC2NVweS/dA7aq+K4adVrjwVGXs1zq1lHO0RERnxtg5AshNtjqHLqfUlktyhO4BDOqKVt7njYtlYyT6zoFqVMjK8y93mU0PbK3s/Kdw4qA1SCXnu5lhwWFrmmn7ym2eTAt7VNA/OHnMQfRpSdtcoHhExweUEEMhFLuUY9hSNofZOS16OaMdGw
  template:
    metadata:
      name: cloudflare-credentials
      namespace: external-dns
    type: Opaque
