---
cluster-api-operator:

  core:
    cluster-api:
      namespace: capi-cluster
      createNamespace: false
  bootstrap:
    kubeadm:
      namespace: capi-cluster
      createNamespace: false
  controlPlane:
    kubeadm:
      namespace: capi-cluster
      createNamespace: false


  configSecret:
    name: cloud-credentials
    namespace: capi-cluster
