netbird:
  fullnameOverride: netbird
  management:
    configmap: |-
      {
        "Stuns": [
          {
            "Proto": "udp",
            "URI": "{{ .STUN_SERVER }}",
            "Username": "",
            "Password": ""
          }
        ],
        "TURNConfig": {
          "TimeBasedCredentials": false,
          "CredentialsTTL": "12h0m0s",
          "Secret": "secret",
          "Turns": [
            {
              "Proto": "udp",
              "URI": "{{ .TURN_SERVER }}",
              "Username": "{{ .TURN_SERVER_USER }}",
              "Password": "{{ .TURN_SERVER_PASSWORD }}"
            }
          ]
        },
        "Relay": {
          "Addresses": ["rels://netbird.vpn.obmondo.com:443/relay"],
          "CredentialsTTL": "24h",
          "Secret": "{{ .RELAY_PASSWORD }}"
        },
        "Signal": {
          "Proto": "https",
          "URI": "netbird.vpn.obmondo.com:443",
          "Username": "",
          "Password": ""
        },
        "Datadir": "/var/lib/netbird/",
        "DataStoreEncryptionKey": "{{ .DATASTORE_ENCRYPTION_KEY }}",
        "HttpConfig": {
          "LetsEncryptDomain": "",
          "CertFile": "",
          "CertKey": "",
          "AuthAudience": "{{ .IDP_CLIENT_ID }}",
          "AuthIssuer": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo",
          "AuthUserIDClaim": "",
          "AuthKeysLocation": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/certs",
          "OIDCConfigEndpoint": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/.well-known/openid-configuration",
          "IdpSignKeyRefreshEnabled": false
        },
        "IdpManagerConfig": {
          "ManagerType": "keycloak",
          "ClientConfig": {
            "Issuer": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/.well-known/openid-configuration",
            "TokenEndpoint": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/token",
            "ClientID": "{{ .IDP_CLIENT_MGMT_ID }}",
            "ClientSecret": "{{ .IDP_CLIENT_MGMT_SECRET }}",
            "GrantType": "client_credentials"
          },
          "ExtraConfig": {
            "Password": "{{ .IDP_SERVICE_ACCOUNT_PASSWORD }}",
            "Username": "{{ .IDP_SERVICE_ACCOUNT_USER }}",
            "AdminEndpoint": "https://keycloak.vpn.obmondo.com/auth/admin/realms/Obmondo"
          },
          "KeycloakClientCredentials": null
        },
        "DeviceAuthorizationFlow": {
          "Provider": "hosted",
          "ProviderConfig": {
            "ClientID": "{{ .IDP_CLIENT_ID }}",
            "ClientSecret": "",
            "Domain": "keycloak.vpn.obmondo.com",
            "Audience": "{{ .IDP_CLIENT_ID }}",
            "TokenEndpoint": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/token",
            "DeviceAuthEndpoint": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/auth/device",
            "AuthorizationEndpoint": "",
            "Scope": "openid",
            "UseIDToken": false,
            "RedirectURLs": null
          }
        },
        "PKCEAuthorizationFlow": {
          "ProviderConfig": {
            "ClientID": "{{ .IDP_CLIENT_ID }}",
            "ClientSecret": "",
            "Domain": "keycloak.vpn.obmondo.com",
            "Audience": "{{ .IDP_CLIENT_ID }}",
            "TokenEndpoint": "https://keycloak.vpn.obmondo.com/auth/realms/Obmondo/protocol/openid-connect/token",
            "DeviceAuthEndpoint": "",
            "AuthorizationEndpoint": "",
            "Scope": "openid profile email offline_access netbird-api",
            "UseIDToken": false,
            "RedirectURLs": null
          }
        },
        "StoreConfig": {
          "Engine": "postgres"
        },
        "ReverseProxy": {
          "TrustedHTTPProxies": null,
          "TrustedHTTPProxiesCount": 0,
          "TrustedPeers": null
        }
      }

    podCommand:
      args:
        - --port=80
        - --log-file=console
        - --log-level=debug
        - --disable-anonymous-metrics=false
        - --single-account-mode-domain=netbird.vpn.obmondo.com
        - --dns-domain=netbird.selfhosted

    ingressGrpc:
      className: traefik
      tls: []
      hosts:
        - host: netbird.vpn.obmondo.com
          paths:
            - path: /management
              pathType: ImplementationSpecific

    ingress:
      className: traefik
      tls: []
      hosts:
        - host: netbird.vpn.obmondo.com
          paths:
            - path: /api
              pathType: ImplementationSpecific

  signal:
    ingress:
      className: traefik
      tls: []
      hosts:
        - host: netbird.vpn.obmondo.com
          paths:
            - path: /signalexchange
              pathType: ImplementationSpecific

  relay:
    env:
      NB_LOG_LEVEL: info
      NB_LISTEN_ADDRESS: ":33080"
      NB_EXPOSED_ADDRESS: rels://netbird.vpn.obmondo.com:443/relay
    ingress:
      className: traefik
      tls: []
      hosts:
        - host: netbird.vpn.obmondo.com
          paths:
            - path: /relay
              pathType: ImplementationSpecific

  dashboard:
    enabled: true
    env:
      # Endpoints
      NETBIRD_MGMT_API_ENDPOINT: https://netbird.vpn.obmondo.com:443
      NETBIRD_MGMT_GRPC_API_ENDPOINT: https://netbird.vpn.obmondo.com:443
      # OIDC
      AUTH_AUTHORITY: https://keycloak.vpn.obmondo.com/auth/realms/Obmondo
      AUTH_SUPPORTED_SCOPES: openid profile email offline_access netbird-api
    ingress:
      className: traefik
      tls: []
      hosts:
        - host: netbird.vpn.obmondo.com
          paths:
            - path: /
              pathType: ImplementationSpecific

coturn:
  coturn:
    realm: "turn.netbird.vpn.obmondo.com"
    auth:
      existingSecret: netbird
      secretKeys:
        username: turnServerUser
        password: turnServerPassword

externalDatabases:
  netbird:
    logicalbackup:
      enabled: false
