apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: 20.1.1
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/sealed-secrets
      targetRevision: 20.1.1
      helm:
        valueFiles:
          - $values/k8s/staging.local.archi.com/argocd-apps/values-sealed-secrets.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
