---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAJ7ZeRMgDm8KQ3bptnNCiuoTNxO7BzVrh+rYWwOI2bl420FAvwTPtCkeTQWVqoZIWFFToLAb6XyJS7l0kE+Bqr4rf0p2SEa0t4XTt0g0ofYNZgdXIviyiGiPLYjy/nvsC30XAIWg0kYL3YzXya7Xi+jCMnrwomNRvcCAD3qbOibhkV1qJdz2TEfFMrVs+jfrRpTP5HbR05ATBJTZNBk8hIIzn30sFgVHZp2VO3xC0TZzKitKtzFVnxuaAUSCbkdOxwDo3ouT2zeMKZuskTuZ/b9I5oD0mdo1zuLdDaewiH4AtkQric11iiVVZbfol+mLXei2P7V1KAjtOjxg0jm1qxL+7ngsGYhBj+Ea1JiS7R93xkNy+dNf5XQxmsW8s6yzUB30x7ibGYuys6i9NoztC7lxWy3KYGhU9y9MPDvjMDguVw/7oh+0f1vAtYDmClWA9iVNRPPGPffw2bzim0szbQHNYVdBYGB3b2PEuHu0TubSdb2wK6Y2PybGP4VcqyEMF0lnFLVeA6sGO/lmzWId4woEC+MHiX8eLb5DFxS2dYIld1hpvVOKjYcnr0/JgSPDGZqtUphxIYVh1+5NllKrgwWaqT/gV7NOYaX49CcWwBZtaqm54/2IR/fCyEXziIaXmnUrgSgtw8hvs9+NdI7e4ghBqB7YelW3mrfLazOc6bIK7vfkiOhAqHo9LP+fHOxTd4vKCLBUh2eUSNG0fZO+mMC+pu5g05EvPOnNdncu2DAfOVu4HKAkCPmKjI9UnQTUw7HXz5ej8mGVTzCIM/+zps
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
