---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCM6v2goXq7vAPwZHKtnhupjyT5j46lW035nJ/i1pZPjHdgNOEW350gfsBEy9hOLCabCLQmnsfG6l3Eau8+3XZWmgtjKfuY/tFYugDrgTy898s4ObFX9jQksr9l9JCkWkcbBV0LRgo33NNIZ6iLSI6jEMCFA3p2G5JgMz1hcnujj95xzA8limH83u9nBGJ2AhfYDjW7w7AJjliyEEkOFyz05MM97uwjNlsVAqtPyHCEXb9TZkVWWHoLrDz4vxYXMHg8x9QdF5h/41/Vrr5Li0VETi+VCalscpamTCgf4+1w6j268OlTmHjqAUhhi2FYUmrWrxuNTQXGclbgNMyb0+n8m75kuK4WWDPK8UYWAoSfmMLgvAL8Wn5VZcqZQ0H5XmkaRA0wcZBr3qster2W9wcCu+rgEnAx7soznC8c1aMMmUnIt6j3lIFkf6VKlnwoUukMc6RiDcG6L7w4sVPrK7xIImEcN+P1HwNtZrgODSyGn6IAUu401SccfMMbf9clfFcRt+cJ8vOwzdDpN7o7OwOYsB2LtMpS2sE6/Djj2E/LGm2kgSaG0q0XRAMhoYMCzEh2hAPzeWYLEDHNv3QSz5N8rAWohxwF11NDxyb5xB61YHrU3MqVdQs3Z6DBBQwJ34YdX3ssYhsY63uwFBNYBV0AVFxA2+UGyNUPKGiEqdwWA5k7mVZ3rp9QZ7UHOIlwsyF15sEvnabZSI4FGt0Egd8J3o8rSUvnuPF4lBno3J6n8xxnc/NI2lVvKdVIN1jbFKA0maO9TL0FRNVzNnRzWg2E
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
