---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCE+axqh0OPTark95kGPryPqNjVwiEz7raBUpR+NFP8n2sHLIkQ0d61D4ED2nA1LFmhwdYXI9Lju6r/6KUvnVg3gi+uFlhAzBkD+0fRolnjiPmr08bZl4SYS7kUi8DBiZt8tHq3+HY5bIwJt8whHBwX+QQFArC/5Slvc1SJD7YfXqCDFg8SPPjP4GVq97b8FNYzkwQn/dev5Wuxs1DFONEw9GDRXHTwTcvwHU1r2MI3CY+JK3ID4PJOQNiGRj8wmMUKkQXZeSMWAGWT5DvGBQeg+wrEeKNyPZZpdzkql1Fn7j1dxSZkU5iMNP9LLj424LZmOrCPMb4qClQINmb4/gyKTVPCG5KtzN1V+1ENcYDe6Dbyv2RZMHMHM6N2JWR4F130xc09wbdpxC0RLEx5CI0zGWXRnQ0BVExbC5MIEOfIM5GruFAN9QQ16Bdb3qnEFTgyTT+3DTXN/tjXvlS5N74Xm0F8HG6uL3wnTJaOu0o6uc3s0PXM4iKt4DGqeY5gL31bi8mmMhwbC0XeSwYRXDx1NZBTgfFumgHOM4sUx9YfuFBn35W0/nujHs3C2u/HKOvSfgccgwp9FwtzTxFWkwRwBtpba1vzl/w5VkrRVjibJiajPKrmLN4ZOC0tDvIOnUblTIPFHVlNQaCNUyeFdyIKhjkF7Ul6as2pVbGAtsR+AeM1mlyDfdcffdcLhkeNnBn3sGMEYkbsG1q15dLXojeFw2cn7ajn9y9Ll0h0WJhc0i7KAeLGdMD+TmXQ7qB9y5g3Y9yP75jy4Hesv0uRH3Xz
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
