---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCU8xMmSrawxyliBeMfOYutXLyQoHEEAgj6F5Q9aW5YHXMdJR2cl+cq4HhaHH8bUQ/KRUM7FD3yfOLBcVSzKMFvSPS5PGEbf2PBtuOYj9z/oVCcTRLnT8AccS/JAzbq0OTz+Y8UcU0LmnBlW6oYceTv5ttCCy/9U5rd/WC+8HbvGrQJRp2AlyFLFIVCPyzK0oafThobFFCDyJKdlll2e/isTVemTbOdLI/EMMxsMude48vs7kyP5pYeCo8Vplbd4Ow41Baee300TCjWz3IeOP2ihvubkX+l3z08yHKNgQdqEsyKLUcxaWE65Vpb/Yp4lTNqvRiiwbnbzlFgaKvymJ9LWzC+Gg5PMFc5TFmJCV2UbjMfR40pa1Dbz6PSGsUhpLvcP/HZDvEU0kGZsb7Z7IOjuzgo/xRUDBoSNYCFnQgPtMK4/mV5V3BYNTPTVbCPlQOHQRkX+Be3AiuzmqIeNMh1rKChRGO3FHJ5qwOsVOYrsmEEorvMII3Tqn6eCB6xKvz3SMG5omgeEVh840TEmX/gZ+U90u1yBZbT40aDoDhTvgNlxtFzqOUT2h/F5B/+INYx9zybwTcqoNhO9BRn+m/MH8LMG3FUlfKTiWyScIwWVVqxgrrSmzZyJDdUBOiF0+IP5uc+g96sL45pawsDIKmXYR5c6TQRQNzp+pb9INy0jEO0++cvon6BAhcAvPKVsP0hs1iD0/5T7w5cn8Uu5hSKdcALZ8NPiGAQ4qtmMGVpyif2ztrALmLzTAKRq/Ti9y+31eiMwN9TCarmviSUPohP
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
