---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBI1qEpFAtcq9rhjCRvJUIqlv3aj3oXpFBDQz1PKUktnRximbdk4WXzucMAQVNkg4GK6ja5PrLIi7FFcUGcmbZI64Z/QK97CMsxNz83WFTssII6xXFHXkDxbuerIKx7i5a3eBnGc7obSQpy8ZReTbBhwVw1n61nS232ITj9BjDK4g2xKnIKKEpVOqRwkswnSOAhUhtvQzFbWhYfdSmFvrPsXVbb79V1vOwjte2/1IT0MT8TDuZxOKstBNiQho4H45VjFxiWGHsEV5B02B/reVrhX4bHYxt/ZwwwTCfWuz0lzDq0QQiWVXwz1WdZUQ+jwtwhjJS+NHsRLEnRmV9yp73x4m+AGRFEh4kHcCg/7Y0Qsfr/w4be1jdOp/3yG3A5PFOHg2LfFXRY9Yoz7nM+fHoTw7ViTmu5CZyxsU+b14ylESjCLT5IaCO6Z15l/OcBAQvolcUU815uYb22oKYeqQ+9VpWOfjwQqW5tYfeFx/ewhV0ER0HzsfErf66LlTusZOG/V97DVl+vrfQQS4XOI95J1OUOfjbfbyBaqJ1yO8cED6771ZVq9Ho2emTS11xGcHPGCIYV5HDb442JfJFN6LxXTsN2s16dnFeWPUFedkNEHEaH+5Fvp4KskOsGVkQDROtH39cADDudc7CVFZwPVKdMP139EPtyqauf2IIES8pY8CZvNIIPMK2XSsQSTIkILHmdVSqyxWZV/gdkDD5/avIv/RdtcfHewQExmiBlKe7SutPafvIYmWAdHf2txRjQC3cYViwCPMXTgWUHCm0hA8sl
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
