---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBfw0K9q/rn7dFcqAPZN/EYpPyC60FW9nko3Z07tUR97kfSwKzZaLTj1W0iyLlkEhGcxVB873dIu/zKsmCPeEnBlVyXb4O5q5t5a4goOe/R8Eg9c+Xi8/QHlKyZYGUk+fk8P2u8efNJEESr2DnO+lCS7UsA8YftP3CIVeEPcY+Ry+jhx6mFOtERDOQTpDtPajp6tfzAShb5qT1C22dhBGw0cs7N1fg+TS+OzY+oM/XctKy/29u6+GFQvTK2FOAHtAkQW+DlgCQov5ZChzwvUalvBiy3OfTJzgKvmST0L2La4M3m3mpqKeZnx7mNJUw6QHbwI8oRTvLQbr1Kp8ClX4rLPp7iNjeU7b/gFpDl1Jce74L9Rbxudw3jZGOchTyklatyCbDMhv4Zn2H2nh5rLY9x80fh4bwUilGs/ragTdduH6/GSP+TlGomgv/bqjVQ6wMiu+Ej7riUQUGk9u2Znb6Ns3o4vJI2s+luDwo8C9hLooSFo5nmaYjw7PQTTAjblsw53dr7ApM8bg4lQp0xeWhmagOgNBIJnphKU1iio4l5XA39Sc4qhqYQ2kKYQp4BtKG81kO4ZFvumutM4lhAZ2rrgsXmF8NXeS1+51yzdN+hcb+Kl+v2sWGMMys7d/rFNnilFTepCc9sQ2RdYyqkAg9LSPHhuWhz2woXpu7q1dKWDDp+FeC0hiKeF+/bqB7LEWrtxdvpwutwLOqwsmS6e4dPI52W4B8Ztbp+U2Ixc7RKSk5Ch9LXaQjRuwCdvhyZWqd03mjLOGDC+8cJtzSLmS/i
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
