---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAXLcrPDFMAr7GLsa1JqUEihwrDh/rnaDph0pIwcIWgxP6kh9sIJdB7zm/+U2cVElsWs5B+zB/VXnVp0kCVcsuUmjJSuJpcPxYfrdsGryU1noe/A/1abLhU3pNDE1fXa4J0d6phycwpc8ASnL6Fg096O64uMOteNnvfp4Um31LYXUN9saBo/FHNnRsv7ZymzDY8XGWR02WKRUCMIwSQSYOzTR71XKfDOwEBZ/VLPmKsu+8xFLJZZHZ9Ct9t4cA2TArv4W7yBiRJaYQpEUrEh7P/cZG7A32m5SzE70fGScM0jYKuS4oiVgxEvRp0R82nGU/YpWDkADg5MHlO3rGBk7HzW4fA7RRC/17KYHlLQ2fbpFkKbSTzlL6Z95fOZ7eoH2EMp+rZWQBaTvNdVmVMMbYhBMhIavvNrgxr5XRd16tb4l80tC9MOMY+4PdkJq8fXvygSB95ocYdU+gXQenXVqKymQEIw3c9gYDbFps2pvEKFUWXGYPziAc94ddtOvh9LLdkFeL8gk/Xw1ubNXiDZO4JSFfTZKWggKFfG/clwMx58Fe7hClKx3ACCoXMTfI71ExY2q+KQtcFrWX0Qyn0ffrku4TShHT+rXZJh7ygUfpdPFeZUrkmLhl1nL8UCmMAydbghY3k/ut0dpixd6vMfakZltVrjYe8Uxqn1kcLdR2cvUJ6x+ht4iG4XWvBUimcwzDGkTx+6zvFv/N2IQDAxMymlfCXKQNVf+VPd1bTOhFXbQWme068fb7wUaUz2xxoLCIlIz2tUASzqVB/ovjiRrxF
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
