---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBD8iQgYBbuxR80QRf19wIm0OFog/+JDkXko0BXIbX/cMhKYNJNe6MnxhvmJ1nXFUznAM9fAMGWY1iwjW8jM0Pp2v2uTH8m7O2HxDdnRIxA54WJa2pHlfZAodaXvSuLbyNn6W7367KjXEaLc3O0pTOM3LhWSHddDDnzbPvPnKpYNiAyFrvsp5aeC6wWf1y0qOabbaF6HEzsPWowj8i5qevozXSsDqONUmGF+YWyLdmM4BaXck7q3hNJ4BmREGvmUD8DDQcVozJRmdQehXLm6C46G5+iLlK0YhIR3VqnjuLs6z/n/RUW4+qJXwJcu/WdWYYcJLSSXhMUyzDMLkuMqSdd3MhOIM0lHyqnXqyVDLTuozOUnheGkeD4Zb4OY3RwAbbf9JTTWUPSeZinbE533Bn4blWB0Ej7lWp/JZrINDI3qDLTOzh8YYDS2ZwsvgQoa6/4rrXGNkG/XjHL7vBqpyX5YyE6S6rHw7BWj6O/si8gLpaZhKUEDDgQLhaBOCYlka4r7upN/0xGQTuQ8NCmLm/tg4h8wcn7IwiWkMz7t1oRimSXR9sirKX4OXGoMbuYop+evYwY4PzYOEWBVpYG0aEgss6BinlVBeYmJQcdRshBS2mKdq1MURUtXkE5QGQJnO9EIsdYUrqr3am4oKVUUp0n3OUEt+VVjTv3oxqiG3/gAdh8qEpAoDH7ZiSt9oNUEIFGq7jLPMimGFKJ5tm69nXRla5HzgyT1G7YZItGsLlFyJ51zs+ne8flAXV0ZoUy9tRmuDFt75527hqWrqYjEJJy
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
