---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgB1ssK+P4yRrE/KiKBjschF3xTTDTU0AfO/vtRi9aI16KJsVoVrNNKkC44QUi7VUbww458iJaVfpOw7cEdUrGKAss2Xqh/aPAWxQz0kIA0x9Q/dJYZM4IvZ6m0Avzv8ZJJ0Ami3gO29f9coRGUe9GfRTB5TasmjovoaQlV+XwjK5uA9Kem5KUbF/ohKSqNK4oTy+CMYsafs472emBPiaUxIxOoscvDmAN3Wgfn69m5QNCWElk2B+NcSB0d5WVb6bV7G6fnlJ8zoQij5+YGefMtt67jmjWp8vLERA8AURRj207VZnSIC9cPEy1hO1ZO8syKrkw6W5j5dhFO/Vvxv5NtCdN6Jdc/VhH4w+V5zHQjIBKw0vmDmdHoIyOLG/vJY/RTRlMbeAl4zQ++exT/AbP8wye3awHBY67alCqDOV4/P3YgGXS9bEGMgHkeQG+ooKI9SNtrY8SBnLtou4YYXPbpgx30Gbn1ZlqZd+hjOZ1kaacPsMg3ojM7Pw49/NNcyKBmSE/magbCEM7iPJcXsAy6JRTATAdWs6no5X68/QSBzBMN6bHF2zV6K2U8vBVoT5GYu8xz7k9HA2mKUQGHsjEwWzmIHK7YCTUzqXmthLeroUmUNHM3aEnA5+7wLwvv3EpRV6+PnT2SJ8URdcagVnbkiPgQ6cDRJDGuOv3tXaTOMgii2dIaCvBTxBgmN3jWvvIBVNSdaP65veFHF6G0EnOf6ONGJK8h8RWUzaJYhAWXWfsjx/s9PNN1DqWsc1ggtngwSrquC/KwUPjudl+Mu81iw
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
