---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCDUn8slp35/KJsU5wm0+xoX0mtKudOzIBnwVmf2iAq38JKoCEt+TEcr8XbEuHDt4PSUss9FQKVYxSmxs8ouBV1CUGY8d97rTTX3p0cM4ppYil+xu32roLBqeGRdeFjFVzAj/81MdFyFUKo5rVSQIULSgfbAjBA53tNhNuccH9AJHdkJ1gTSaBjN75EdlNANJNdTGRAGQZ2SIDpi6/N1k+FR8JBQn9ZX0vPuZmgQFPrdg0Dl57PcOZ15v4gzmflwQ59HZH3PdIBAoGyhcvOO+c4XKwh+GSLTFCApmkVnEfaXh5gl4J8jSEySC5rFJDQW47LAiD1SdLL10CfxJann973g8DWleIgkyXCzC51wmeSZ47ZdQzZZapyOQzOIafa3anKKlUbZY7ClO/7rnBiYhuxaWw0Go6JsTZBM8q86zNtSoDoDOIXtVh4axlzrBfRSjA5YN6dekeqZXNguRjo6s2JEIpOHAhCYIGL2IbaKEF2OwvGOiNik3fjCEjZj531W61llnT29snyDKQLy/NLWbNkyx3gUUfYySO7erMBxndLmNveHoyeIem7r5qCCeoiofJpM8lPsuU2WXs8V9RHk8ruMMVe5hoPY9uzhyhlXP4sytYNlWdarbIn+BsfAh0JqIQnlc9jFC7Sapn+cVi0aARI7a+N5FMIw1XQn7FNBUOTC2u9gRCqXqrgHZfp8PAHbEf74+GkYf6xD6hyPEnX5n/Ft0MqXXDQ2PCW8SO2MPlRjhoSmiqNAXwSwWVB2NP26Omb+HKa89E4FLdyQ/eVYFsO
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
