---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgC4X12MuXkk5N87jX7/hUPvj30Ont+DC57JsMq6CDPCTaQUYZN9deFk4UBuW5P7HgrAqHuT+WsjvCfizimUZtkE+AYX+ASpr0SCQ86CV80Gh/kZ1WDsac+VEhkhr8GUj0+p0DK9cpV3zQSt28XCLJfOqG1kcm94/ef/qF7gd/XMeI60Jfu7vsCFRDJz4nT+BeVoZjoSUDlrVcnxUw9SNVlbeiYYQH9g1ojQobqAbcxvN/rR/35eO9jedebwEEeh7IXf3yP1cttfP4dp7xBuMkoFWhYXt80QKe4lg/5cUtHMk0GipkdqHEblHpyUZwpbSvWxsFLTLkcLDedwB+4vGtAdtitp5UwUpL48JEev+OGG+zYPTNcntuF6XGVjLmsbC6YY1doyfHkIybPtI97cvPNajZP/MVLUxpWWqAtz4zbg8EL5V6IcbkS1KYrRNOOiYZWI70HFlzsf2dm4x5mlb5PQ3LmzAJI4uXVfovVcgQOFU1Es9Kr/UpGFxk5j68vqNFp8JqZRKCGZPVVECyBh8tjnI53h3zloIRYHxmSGPOWszHrIWDlhvknOws59AFNstWVTNfJc4x/jYu/vDf26WBMcFBC3VoE4rB986QAbeInrR3z+rsDo/WjDpC34g2GKAXnQA98UiLcsaAIP63Q4mf5xZRGowegv2RtLibiezA9S6mYDA0OFnjDRBHuRaEhcGMAJZAROIuTYbIPpxtg6gu/WLQ/QhTjLt6iUxaxqJC+vgTEWw44hU4NHVm8SLrpXrw79P/DJfAsJZ1kZCZuSnZZc
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
