---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBD2M8YLsBc4wcaHIshoFFNRwnhAF9HYzR5pnY2RlSWoUjGezdNp0QjzWIRH+UAUODq3AVvgfzeUqVQmMYaKGNPIEJg+6xsSk1BenixpKUEz48bDWH9PjUM72lRoukMtAbvW8IhJ41U4SdObAdjqCdAMakTG143iKe21r7OYSxvyL8GfcPBtBuY8Z7MUmEADS8vwAsth8r7xl4PK/IL+ljEP+kmfVaGskCaDsO/FkIFEq7amutxAA6B3rsEp+oDfgt7T8n5nr+d7uFePX3wT1EkMbDEtTPx0IQzGIEqOZh6+dlFD4/B0WfZZruJHYTEce9VHG9+gJRRcmXDR09ZIyb3BOUshGazyktUmuWq3RlH2NwQkFT2TC/QiQndiEiKw7bpr3yVcN8NF2PDqD0yr1Ok3XKI69upvRUPVxCgE8RZ3cIFDDQ+ColUkPfUw8rJjVeRXjJJ1ED7c5rAAz6QnO/abGLwoePES29rrpyZYkWIKF/86WGYhrLGWQCWIG3nTeDeDLXSsjl6l4qFZBgVDkHwmr6oqM3+mRUEk4fqfzoO7WUauhOz73/U7ku6C0jgGFEbaY082+13NNtVcFtMuirnELEuhJdGL5+615UeSVAetMHfFvUOp1uhd2OyDuuSeTddYll2sTQwDx+22/MhPnVaQP91d7d4hfacByjyRj50ImlRC93+fF9dgoUa5sSohfIJLTJmoEF3xVcOkjY7lgS2aORWJ6W/Uq7qHfQyZ8Ut9Ia2X0I5SG58uDdCR54kymcS+mmnh/OCBB74l53sivQK
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
