---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgAc6ZWszvfluvI4rXe5n7KE/hg46GiUb6XrR0CR6ncTMlN4G4vACeUIjrksN5v0rfarhMYkuxu3HzAUnvp93XsnTecGuOvI3vkfGdPXAM4cvv4PqJ7TwqGu431UY2BqgM3aSAUM/Sl+KvL0NdLlK1OueK1t9DE+jvO1JaR9cJd4K0upbcpf+ZGRqwJh6vSh0o6fLQUj9FvfIHroIHK37F9c+BSL1mblZYSUAgdXwLglLzsH6AATBCyvUrTCs5f3j7Q8uvTnC/XiyK54+UY1IASqz5bK5jCW7lfcgEKo6c8RLeUfkX1VKBhIo4DXNTaQMAWb3oFN6goz2Hz8MEz3UqnCE3qLNoxm9oOzDxU1bGa0iq/e6FyXiKyMdTa051Lxo2s42MdypbAZ7bg3yeB6BrBYNHgmpLgfdEYey2y4Of3XaLx8QUP6m4QwaU1Z+p3c/BiZ+Za1UM12kiYkpmQWzaimoYBT9JreW1ll8VsifnH4oZD+qOAXiQ1b4h3QkkpaaQko+aYSV7tr44XXeG+fVDt/aS7iZh4Y2iWS9QOUlVX3/yaS9LNxLb0Q6vL4KhwXACCqkcFCmUdZ+bbzjst3mqFOqH3aa2wHzNRE8rZSRp+JzF1EkUvUZ9vC+ny4LKDT7y7SdKalOToJKMiJdlE7rhJMYiTu2onnPUCuJrMy6B+GKEd5QSb1V8aNCHDVe6RjvnAAGz67FdbnpztFGJm3yyms5N7rub7LSCteH5R0kNDFbXGed5WudM24cMwXRxH+d2Am7GDlC0b4meiYNhbMcteW
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
