---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCPbh+XP99tSjoOxKWa84yEfKYu2Z4tSeYdS8ZX41GP8W/9j6gwEvjnNdU1j4SB+NqzqQEB/A2kItTXtkAbOLQAe8CbKABTVP34D6WlrkG5R7g0/byh7ISjDlrHIGiioGJi5PVANYhB2xcrFLjbIjhnrWHicIFR0Gg5V35Wzr2wIlJk9ZGiytRJcWFCpT6jeBFIcUKNtzfYnwv5Gcz9msJCCjid83RfBRQ8vG2KfAfJnZqm0CVQyuosMLbiCAtfxT3us+MTyVf5iJeqAC00UDzRCXCSV2onxp6oyo1KRiOcOwzq6K2Dh/aO+gzXuW9ErojtslywFV7g98c6EY5rDApHKD/g/wN5upo7EBNAWyXclwpLgq8zBlAX1WohQqTHtfPivoZo9jarc4yA5DvOcwGwjlZQk03XHpX6h6z8OcngnLRRuobOwyuJW74XHrV2Ry75Y4VuWiHZQleHpg4jACoKYz5ZLdJ2/RqtZo/mYcrsKo85OCzLBN0Iecj6q9awe2JOnMDq7i1P9CVKeOReIA3W68QmWAg8d0k3SuhAXkYfhBjVOezNtnDP3WTrA4AF2FgalFH6UVoPgGFCU/p1lOzzIX0s4oiUEfXlNYj2dBRjeMQbAC0+mW/VrQhD4FeFyqYG57upjFslujbaNwZSATRISbVdE+5kGv0/Nb42baFcm8aSgFe/IdRHY3i2QP5vEh1eJ74VrgKdJ4uDXUeMupzUgdUq0dplZ+8qb5sHeCDRTpdXmAl8VcA/rQrmHABCJ+3XkXcv0hXb5N+7pj+X5xMC
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
