---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgB5ZbTgRpuZw6r9lC+6119Z7d4/FQl+DzPAIKb3FL9XMKZxUUp4QePgcZcm+bPHTaKQDFFPETYvKXhF+zc17FPQUR+4j0SgbWB3yVXosJzb2m1Dky/DXqtUM/PyhUPwXd47BWSODI2n7l7rTz1Mc3Z708SVq5dYt8VolzuBpSkYW1cYUw9KwHwMb/J/zsgulvqfbACx/WUE+lBOMrgKfSVh33O4YIOwl+mQszMFg6/ZNLZT4C590uG0Ve7QMaCoubIvRGXBeQbxe3nqAP6OMU+WHg/6S9zjbKMI9fXNHOA0NXPKVKJYjpjGI+i4jU7N5aRhy+7Kl8boYKlRpCsEmvvhaV6vSuE5ASEFs4ikqtOKqY9q9TcYXEhsEL/bXL7waAksIweXUqhssHcQBrxSvp0bd2I+xQ+9NVFFbBpjOuc6GL2SpGqDqEO1ANgdw5gWWK9GfM4Ju4hEWqpElRv/bxIiFGO0iO5pfUnJbhSupVtUl5wXFc7qkLC/KICoDC3CusgLz8SMPmtvBzVdicPZv0FV5M2+uYqEhTR+dssYgzGMIbeWZ8wdJc79J8G9wLKoGE2/k7wjqoEFeIiOlU0uFDeS8zbmyOzFcY66SKbp+L2PG4RwZbIf+eMMU0wV9IJw3fuiwwbgjv8ME5ocDDagh8oT239uYsWl704L9rMNADRR8ee06yJV0ljv29d7kNHo3vkMU95UKw5+srd2BgaHREZSSjrM5H9wPsxW6RDuLqm+ltIA4CLpIQVo4IjRT/FOJqx9JG4VYlX+6ZGGVbeSwB+f
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
