---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgA5Fk6xYOV+W2AGOxelmaVic5d9WKLxslOX7wsOVnFHglYE2IpzfMR3oNRybqFg84iTuk0XSiI4Fqq5CmLAgWW5+2fkznO/edcXH1RollSMkdXcr/MTy4D2E6YTc9OHV23d0iv2SvL4dPZsekW4CnVMRp1BL4dc/fwjEe9oFi26zfcN3ZXdCHsrk4XZRXJ2ScqCkyIDmfk0bG9QQ9G7aJFZKaqwc5YHoOewhZOvwQRvcw95TmJD5uP6GQCnf+7oc9uQ1NyB3Th6uRB6NP6tc6tgaqGpO3WqnptUsKfHi4BzMNYR1VmEUKBhPaNU5dYfOQ7KbBY7Y3gphNvYK8tJGLTv9KX1GngZvPXNOj8B75nPW784xVwKDjyqGvHIhyDGuGjmb1jMfGWJosXSn55NvU2Xdmk10OJYIXFZrRYLigNBD4BszBnHktZKKxsEnUpvTcq05RHiLbdk65IoXRBkXubAX+0juwl+8OiaazUQgOYdRyYtfFyHClhbjif4PDqgRp+ofPjhePyYcSN04E6dmYu2dTd9AuoKbdu5mAcSXU3RzUX38jRPgiXwULZ2y+xj/IomflFsO1rliE5HI0M+rENsI+wqxcxRwDgVD3PZZtE++bxptnhdO1aToSYMMmgFbTZS2UHJfQG7Bk58JL6LbWD3e0eUq6U4Oryz0qOdPID72BalYVKryKPzdEhmoArLfz88UFYtW/+225CCSdRd+8RlNqBN+qebq41FT++GyuO6rcxCYHpOIAU4FWzd0J5yO2wpU70eOMNW60RIXpBLdrth
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
