---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBpsPZx6/2eZUwxQLrqzMpEkqphHQX/D6j/ADXY+zgz/2GWHRjS0i2s4g1wj8zbzNrxul4cumFeU+rWUOKJiv3XMpA+gRv7aPcnxmeO+KfFw2pB/lj+4rBSm44+HyJLqKbOLXwUaAGROTSzBLyrEgSfl/jHNTy01TzSRMxIz5EJuiznM8fVORnLCeDM/rfjMSyJFo+Df7/RXVBwjNTkclbH7kFbF2gJuLtU6NHcvTle8q2c0P9m8+X6unTkZLwK+CrYstS+5Po/OAt3b2uHe0LOWKgGBQBp7/cmm/mKBhz6VCiZ1Zx0Zc5kCsaFEN8m1lbBdJ56fPlP78ONf9KQJHcAqV/v7OetdGUXG3mT+ZDTP+cYa3ogbMGKy8kHMtjlNyW2CWDoGVfeaXJy+wIhTdJO7y0r+EU56vYVlwc701Z7FsRgOjYdYIAtfQP400n+0K2ioUrbEkTcXpHFTlWXa0HZInz3i8rL58OzxzU4XMtRVq0qo38bXXYZpBG8LM6gwanS9bnFL58W2PzpfR6nxYbr6qfaqv14sLta3aolFS9uOcxesqrdK9KyZfUmg7evP2jxK2O3Xq/rDklaTR+l3i6iX/itbpnJtAGjzk0+TK6kY38oETIbDZQV79OuleKM1cIaBV2DGALrSOOzDlsLr3/MiIpsDmXHNX9ezlftNvKtMmTg/beVdhWgWz4pJtBOhqyEUVC8+PvQ3bUOj+6Tc6pXud+QEdKKxUA+efP3llfKAsQIimklLJ/ZY4w/n6RKb7/XrvmC6+XVp+lf/G+qUkZi
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
