---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBp6H6QNc4JEjlsqOGSYZAMCycfiovs8+HU1PtSTEWmr4qtE6lO8gvSoeBFRUaiyzybJPTMZnDL5jynA30GLhePbvNbuFEa5lifaRP1c9wJyCBNZDpB766qpz9M7unZSrqNCruMpD7K8MRCq7vyNucmOgXWo/wiUqV+R2iYmDrmUT4n/aH8jSg5JLfKSw84oHNV/SUe4rjuuFPvKK45HauvNr7Aljx3yR51hMH/0sS/FsT32Lzgv8wNFgfnj0GzfrqhaUyyIngu54zBw9kqDn27h0pblvj2QUpljtMheeaBHnpHPoQbrk/mc++dNUpyf7AkHk3LDhVE2xGQqH22Znnc+uEa3uAn0NwRPQFlMQHzADnK3MIxLN2o776i4iGE7GPEhSXH6Us1fZnnvvLg/tCjBR/j6w2iI8SZwXxhvMQ9xnuXiLcg/Mzl0BgktLK2F5/YEJLixdDCXjSUkGO9mbnNiNJCR5Oyp3TAuinXxziKLbKZta7s9+lhBcf+GSIv5jhWS4Xi4mmx3NKN+S06TahcaJlHh8MwR3OjL9tms6KAkAPiGT9fxihaFmFhsNNPhFnRKzGDkkdBowWfV4uDcvZj3y73S3/vLEd+nwSytSiUzWAJ0tPQ5SINXaBJgCXT/65Uw+9ByBrGTiZv1O95gNvb3/RXTWTKE5Z4zrkMLpherFHxSfKcgQjndaNqEMEa1YoZzPahUWt7Q3i640TXKVCh3Yo59s0SxetXRHIn8FH26GVoqCGOAOi9Zi38UJi8qIdYk5X9Lta18dOESJ06h9kv
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
